ALTER TABLE disease_events
  ADD COLUMN IF NOT EXISTS sentiment VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS needs_review BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS event_type VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS event_confidence NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS relevance_score VARCHAR(10) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS relevance_confidence NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS source_credibility NUMERIC(3,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS source_credibility_label VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS event_cluster_id UUID DEFAULT NULL;
