CREATE TABLE IF NOT EXISTS nlp_keywords (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category VARCHAR(50) NOT NULL CHECK (category IN ('symptom','disease')),
    keyword TEXT NOT NULL,
    target_label TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    priority INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_keywords_cat_kw ON nlp_keywords(category, keyword);

INSERT INTO nlp_keywords (category, keyword, target_label, priority) VALUES
    ('symptom', 'demam tinggi', 'HIGH_FEVER', 1),
    ('symptom', 'demam', 'FEVER', 2),
    ('symptom', 'batuk', 'COUGH', 3),
    ('symptom', 'pilek', 'RUNNY_NOSE', 4),
    ('symptom', 'diare akut', 'ACUTE_DIARRHEA', 5),
    ('symptom', 'diare', 'DIARRHEA', 6),
    ('symptom', 'sesak', 'SHORTNESS_OF_BREATH', 7),
    ('symptom', 'sakit', 'ILLNESS', 8),
    ('symptom', 'shortness of breath', 'SHORTNESS_OF_BREATH', 9),
    ('symptom', 'fever', 'FEVER', 10),
    ('symptom', 'cough', 'COUGH', 11),
    ('symptom', 'diarrhea', 'DIARRHEA', 12),
    ('symptom', 'disease', 'DISEASE', 50),
    ('symptom', 'outbreak', 'OUTBREAK', 51),
    ('symptom', 'epidemic', 'EPIDEMIC', 52),
    ('symptom', 'virus', 'VIRUS', 53),
    ('symptom', 'infection', 'INFECTION', 54),
    ('symptom', 'patients', 'PATIENT', 55),
    ('symptom', 'hospital', 'HOSPITAL', 56),
    ('symptom', 'death', 'DEATH', 57),
    ('symptom', 'vaccine', 'VACCINE', 58),
    ('symptom', 'illness', 'ILLNESS', 59),
    ('symptom', 'cases', 'CASE', 60),
    ('symptom', 'pandemic', 'PANDEMIC', 61),
    ('symptom', 'quarantine', 'QUARANTINE', 62),
    ('symptom', 'symptoms', 'SYMPTOM', 63),
    ('symptom', 'transmission', 'TRANSMISSION', 64),
    ('symptom', 'treatment', 'TREATMENT', 65),
    ('symptom', 'positive', 'POSITIVE', 66),
    ('symptom', 'diagnosed', 'DIAGNOSED', 67),
    ('symptom', 'recovery', 'RECOVERY', 68),
    ('symptom', 'health', 'HEALTH', 69),
    ('symptom', 'medical', 'MEDICAL', 70),
    ('symptom', 'wabah', 'OUTBREAK', 101),
    ('symptom', 'epidemi', 'EPIDEMIC', 102),
    ('symptom', 'kasus', 'CASE', 103),
    ('symptom', 'pasien', 'PATIENT', 104),
    ('symptom', 'infeksi', 'INFECTION', 105),
    ('symptom', 'kematian', 'DEATH', 106),
    ('symptom', 'meninggal', 'DEATH', 107),
    ('symptom', 'dirawat', 'HOSPITALIZED', 108),
    ('symptom', 'vaksin', 'VACCINE', 109),
    ('symptom', 'korban', 'VICTIM', 110),
    ('symptom', 'terinfeksi', 'INFECTION', 111),
    ('symptom', 'penderita', 'PATIENT', 112),
    ('symptom', 'gejala', 'SYMPTOM', 113),
    ('symptom', 'penularan', 'TRANSMISSION', 114),
    ('symptom', 'pengobatan', 'TREATMENT', 115),
    ('symptom', 'sembuh', 'RECOVERED', 116),
    ('symptom', 'kritis', 'CRITICAL', 117),
    ('symptom', 'imunisasi', 'IMMUNIZATION', 118),
    ('disease', 'demam berdarah', 'DBD', 1),
    ('disease', 'dbd', 'DBD', 2),
    ('disease', 'dengue', 'DBD', 3),
    ('disease', 'diare akut', 'DIARE_AKUT', 4),
    ('disease', 'leptospirosis', 'LEPTOSPIROSIS', 5),
    ('disease', 'influenza', 'INFLUENZA', 6),
    ('disease', 'flu', 'INFLUENZA', 7),
    ('disease', 'covid', 'COVID19', 8),
    ('disease', 'corona', 'COVID19', 9),
    ('disease', 'covid-19', 'COVID19', 10),
    ('disease', 'malaria', 'MALARIA', 11),
    ('disease', 'tbc', 'TUBERCULOSIS', 12),
    ('disease', 'tuberculosis', 'TUBERCULOSIS', 13),
    ('disease', 'chikungunya', 'CHIKUNGUNYA', 14),
    ('disease', 'pneumonia', 'PNEUMONIA', 15),
    ('disease', 'tifus', 'TYPHOID', 16),
    ('disease', 'campak', 'MEASLES', 17),
    ('disease', 'hantavirus', 'HANTAVIRUS', 18),
    ('disease', 'mers', 'MERS', 19),
    ('disease', 'kolera', 'CHOLERA', 20),
    ('disease', 'polio', 'POLIO', 21),
    ('disease', 'rabies', 'RABIES', 22),
    ('disease', 'hepatitis', 'HEPATITIS', 23),
    ('disease', 'antraks', 'ANTHRAX', 24),
    ('disease', 'cacar', 'SMALLPOX', 25),
    ('disease', 'zika', 'ZIKA', 26)
ON CONFLICT (category, keyword) DO NOTHING;
