-- Store the deterministic evidence-preserving summary generated by NLP URL analysis.
-- Nullable for historical reports; existing source content remains untouched.
ALTER TABLE raw_reports
    ADD COLUMN IF NOT EXISTS summary TEXT;
