-- Restore ABVC Alma catalog categories onto sources seeded as generic "web".
-- Collector engine type stays rss/web/social_media/api so scrapers keep working.
-- Catalog type/official status/from_engine are stored in config for the UI.
-- Sources remain disabled.
BEGIN;

CREATE OR REPLACE FUNCTION abvc_source_credibility_type(config jsonb, source_type text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE LOWER(BTRIM(COALESCE(NULLIF(config->>'catalog_type', ''), source_type)))
    WHEN 'official government sites' THEN 'government'
    WHEN 'local news' THEN 'news'
    WHEN 'google' THEN 'web'
    WHEN 'facebook' THEN 'social_media'
    WHEN 'html' THEN 'web'
    WHEN 'chart' THEN 'web'
    WHEN 'json' THEN 'api'
    WHEN 'xml' THEN 'rss'
    ELSE LOWER(source_type)
  END;
$$;

CREATE TEMP TABLE abvc_catalog (
    source_url TEXT NOT NULL,
    catalog_type TEXT NOT NULL,
    type_id INTEGER,
    validity_status TEXT,
    from_engine TEXT
) ON COMMIT DROP;

INSERT INTO abvc_catalog (source_url, catalog_type, type_id, validity_status, from_engine)
VALUES
('https://163.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://1news.co.nz/', 'Google', 3, 'Unofficial', 'Yes'),
('https://24h.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://24hmoney.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://24newshd.tv/', 'Google', 3, 'Unofficial', 'Yes'),
('https://3g.china.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://4gtv.tv/', 'Google', 3, 'Unofficial', 'Yes'),
('https://52hrtt.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://7news.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://9news.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aawsat.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://abcnews.go.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aboluowang.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://adaptresearchwriting.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://afamily.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://agora-web.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aha.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aktualtangerang.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://albiladdaily.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aleqaria.com.eg/', 'Google', 3, 'Unofficial', 'Yes'),
('https://alloranews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://alobacsi.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://alparslandiyari.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://alwatannews.net/', 'Local News', 7, 'Official', 'No'),
('https://ameera.republika.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.9news.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.baodautu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.cand.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.dw.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.laodong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.modbee.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.suara.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://amp.vtcnews.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aninews.in/', 'Local News', 7, 'Official', 'No'),
('https://anninhthudo.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://antifakenewscenter.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://apnews.com/', 'Local News', 7, 'Official', 'No'),
('https://app.myzaker.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://arabstoday.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://artthreat.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aruna.lk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://arynews.tv/', 'Local News', 7, 'Official', 'No'),
('https://asahi.co.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://asianews.network/', 'Local News', 7, 'Official', 'No'),
('https://astroawani.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://au.news.yahoo.com/', 'Local News', 7, 'Official', 'No'),
('https://au.sports.yahoo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://aydinlik.com.tr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ayokaltim.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://azat.tv/', 'Google', 3, 'Unofficial', 'Yes'),
('https://azernews.az/', 'Google', 3, 'Unofficial', 'Yes'),
('https://babel.antaranews.com/', 'Local News', 7, 'Official', 'No'),
('https://babelinsight.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bacaini.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bacninhtv.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baguio.bomboradyo.com/', 'Local News', 7, 'Official', 'No'),
('https://baguioheraldexpressonline.com/', 'Local News', 7, 'Official', 'No'),
('https://bali.antaranews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bali.idntimes.com/', 'Local News', 7, 'Official', 'No'),
('https://bali.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://baliexpress.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://baliportalnews.com/', 'Local News', 7, 'Official', 'No'),
('https://balitribune.co.id/', 'Local News', 7, 'Official', 'No'),
('https://bandung.kompas.com/', 'Local News', 7, 'Official', 'No'),
('https://bangaloremirror.indiatimes.com/', 'Local News', 7, 'Official', 'No'),
('https://bangla.bdnews24.com/', 'Local News', 7, 'Official', 'No'),
('https://bangla.thedailystar.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://banjarmasin.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://banten.akurat.co/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bantenraya.co/', 'Local News', 7, 'Official', 'No'),
('https://banyumas.viva.co.id/', 'Local News', 7, 'Official', 'No'),
('https://baobacninhtv.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baobinhdinh.vn/', 'Local News', 7, 'Official', 'No'),
('https://baocantho.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baochinhphu.vn/', 'Official Government Sites', 4, 'Official', 'No'),
('https://baodaklak.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baodautu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baodongnai.com.vn/', 'Local News', 7, 'Official', 'No'),
('https://baodongthap.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baogialai.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baohaiduong.vn/', 'Local News', 7, 'Official', 'No'),
('https://baohatinh.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baohiemxahoi.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baokhanhhoa.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baolangson.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baolaocai.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baomoi.com/', 'Local News', 7, 'Official', 'No'),
('https://baophapluat.vn/', 'Local News', 7, 'Official', 'No'),
('https://baophutho.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baoquangninh.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baoquocte.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baotayninh.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baothainguyen.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baothanhhoa.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baotintuc.vn/', 'Local News', 7, 'Official', 'No'),
('https://baotuyenquang.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://baovanhoa.vn/', 'Local News', 7, 'Official', 'No'),
('https://baovinhlong.com.vn/', 'Local News', 7, 'Official', 'No'),
('https://baoxaydung.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bastillepost.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://batampos.jawapos.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://batuahnews.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://bbc.co.uk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bdnews24.com/', 'Local News', 7, 'Official', 'No'),
('https://beartai.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://beautynesia.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bekaci.suara.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bengkulu.pikiran-rakyat.com/', 'Local News', 7, 'Official', 'No'),
('https://bengkulu.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://benhvienathainguyen.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://benhvienducgiang.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://benhvienthucuc.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://berita.mediacorp.sg/', 'Google', 3, 'Unofficial', 'Yes'),
('https://berita.rtm.gov.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://beritabuana.co/', 'Google', 3, 'Unofficial', 'Yes'),
('https://beritaharian.sg/', 'Google', 3, 'Unofficial', 'Yes'),
('https://beritajatim.com/', 'Local News', 7, 'Official', 'No'),
('https://beritamusi.co.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://beritanasional.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://betanews.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://bidiktangsel.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bioengineer.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://biz.chosun.com/', 'Local News', 7, 'Official', 'No'),
('https://bloknot-stavropol.ru/', 'Local News', 7, 'Official', 'No'),
('https://bloknot-volgograd.ru/', 'Local News', 7, 'Official', 'No'),
('https://bokra.net/', 'Local News', 7, 'Official', 'No'),
('https://bontangpost.id/', 'Local News', 7, 'Official', 'No'),
('https://borneobulletin.com.bn/', 'Local News', 7, 'Official', 'No'),
('https://br-cn.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://brandiconimage.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://busam.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://businessday.ng/', 'Google', 3, 'Unofficial', 'Yes'),
('https://businesstimes-bd.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://bvdl.org.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://c.m.163.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ca.news.yahoo.com/', 'Local News', 7, 'Official', 'No'),
('https://cafebiz.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cafef.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://calgaryherald.com/', 'Local News', 7, 'Official', 'No'),
('https://calgarysun.com/', 'Local News', 7, 'Official', 'No'),
('https://canadianrecord.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://canberratimes.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cand.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://capeyorkweekly.com.au/', 'Local News', 7, 'Unofficial', 'No'),
('https://cauayan.bomboradyo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cbn.globo.com/', 'Local News', 7, 'Official', 'No'),
('https://cbnews.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cbsaustin.com/', 'Local News', 7, 'Official', 'No'),
('https://cdo.bomboradyo.com/', 'Local News', 7, 'Official', 'No'),
('https://cebudailynews.inquirer.net/', 'Local News', 7, 'Official', 'No'),
('https://ceklissatu.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://celotehriau.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://centralluzon.politiko.com.ph/', 'Local News', 7, 'Official', 'No'),
('https://cesphn.org.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ceylontoday.lk/', 'Local News', 7, 'Official', 'No'),
('https://channelstv.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://chatnewstoday.ca/', 'Local News', 7, 'Official', 'No'),
('https://chiangmainews.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://chibanippo.co.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://chimpreports.com/', 'Local News', 7, 'Official', 'No'),
('https://chinacdc.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://chinapress.com.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://chinhsachcuocsong.vnanet.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://chuyendoiso.baoquangninh.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cirebonraya.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://citinewsroom.com/', 'Local News', 7, 'Official', 'No'),
('https://cityhub.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://citynews.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://citynewsqbn.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cj.sina.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ckpgtoday.ca/', 'Local News', 7, 'Official', 'No'),
('https://click2houston.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cmmedia.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cnn.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://cobisnis.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://coloradocountycitizen.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://congan.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://congdankhuyenhoc.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://congly.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ctee.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ctinews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ctwant.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dabangasudan.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://daibieunhandan.vn/', 'Local News', 7, 'Official', 'No'),
('https://daidoanket.vn/', 'Local News', 7, 'Official', 'No'),
('https://dailyasianage.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dailyguardian.com.ph/', 'Local News', 7, 'Official', 'No'),
('https://dailyhive.com/', 'Local News', 7, 'Official', 'No'),
('https://dailyinqilab.com/', 'Local News', 7, 'Official', 'No'),
('https://dailymail.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dailynews.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dailypakistan.com.pk/', 'Local News', 7, 'Official', 'No'),
('https://dailypost.ng/', 'Local News', 7, 'Official', 'No'),
('https://dailytelegraph.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dailythepatriot.com/', 'Local News', 7, 'Official', 'No'),
('https://dailytimesng.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dailytrust.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dairi.wahananews.co/', 'Local News', 7, 'Unofficial', 'No'),
('https://daklak24h.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dangcongsan.org.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dantocphattrien.vietnamnet.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dantri.com.vn/', 'Local News', 7, 'Official', 'No'),
('https://danviet.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dap-news.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dayakdaily.com/', 'Local News', 7, 'Official', 'No'),
('https://ddc.moph.go.th/', 'Official Government Sites', 4, 'Official', 'No'),
('https://denpasar.kompas.com/', 'Local News', 7, 'Official', 'No'),
('https://dentonrc.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://devdiscourse.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dhakaprokash24.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dienbientv.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dienbienv2.mediatech.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://digicastnegros.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://dinkes.acehprov.go.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dinkominfo.demakkab.go.id/', 'Official Government Sites', 4, 'Official', 'No'),
('https://disway.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://divaina.lk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dmgburmese.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://doanhnghiepcuocsong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://doanhnghiepkinhtexanh.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://doanhnhan.congly.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://docnhanh.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://doisongphapluat.com.vn/', 'Local News', 7, 'Official', 'No'),
('https://donga.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dongascience.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dongnaicdc.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://downtoearth.org.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://drimble.nl/', 'Local News', 7, 'Official', 'No'),
('https://dtinews.dantri.com.vn/', 'Local News', 7, 'Official', 'No'),
('https://dtoday.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://dw.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://e.vnexpress.net/', 'Local News', 7, 'Official', 'No'),
('https://eastbaytimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ebiotrade.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://economia.uol.com.br/', 'Local News', 7, 'Official', 'No'),
('https://economictimes.indiatimes.com/', 'Local News', 7, 'Official', 'No'),
('https://edaily.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://edition.cnn.com/', 'Local News', 7, 'Official', 'No'),
('https://egypt-today.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ehealth.eletsonline.com/', 'Local News', 7, 'Official', 'No'),
('https://ekonomi.espos.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://eksposkaltim.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://elevenmyanmar.com/', 'Local News', 7, 'Official', 'No'),
('https://elhadaf-sd.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://elpasomatters.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://en.antaranews.com/', 'Local News', 7, 'Official', 'No'),
('https://en.freshnewsasia.com/index.php/en/localnews/60685-2025-06-02-08-02-09.html', 'Chart', 12, 'Unofficial', 'No'),
('https://en.sggp.org.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://en.tempo.co/', 'Google', 3, 'Unofficial', 'Yes'),
('https://en.yenisafak.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://enbeauce.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://english.aaj.tv/', 'Google', 3, 'Unofficial', 'Yes'),
('https://epaper.tkww.hk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://espn.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://fajarpapua.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://fiercebiotech.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://fili.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://filmogaz.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://fk.unair.ac.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://flores.pikiran-rakyat.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://focus.scol.com.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://fountmedia.io/', 'Google', 3, 'Unofficial', 'Yes'),
('https://foxnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://france24.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ftnn.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://garuda.tv/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gbcode.rthk.hk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gcc.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gefluegelnews.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://geraldtonguardian.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://giadinh.suckhoedoisong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://giaoduc.edu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://giaoducthoidai.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://global.hk01.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://globenewswire.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://go.seoul.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gocnhinphaply.nguoiduatin.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gonews.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://goodmorningcc.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://goodnewsfromindonesia.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gossiplankanews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://greekherald.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gulfnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://gyeongsangtoday.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://haberglobal.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hakkanews.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://halosemarang.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hanoionline.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hatinh.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hawaiinewsnow.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hcdc.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://headline.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://health.detik.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://health.kapook.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://health.kompas.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://health.ltn.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://healthandme.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://healthbeat.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://healthnews.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://helenair.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hellobacsi.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://heloindonesia.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://herald-dispatch.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hfocus.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hindi.awazthevoice.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hindi.downtoearth.org.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hindi.latestly.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hindi.news18.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hindi.theprint.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hk.epochtimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hk.on.cc/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hk.ulifestyle.com.hk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hk01.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hkcd.com.hk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hntrbrk.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://homeophyto.topsante.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hpj.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://huengaynay.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://huxiu.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://hypeabis.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ibc24.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ibtimes.co.uk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://idomavoice.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ihram.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ilgazzettino.it/', 'Google', 3, 'Unofficial', 'Yes'),
('https://imaeil.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indailysa.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://india.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indianews.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indianexpress.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indikatorbisnis.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indonesia.focustaiwan.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indonesia.go.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indonesiaexpat.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indonesiakini.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://indonesiare.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://inet.detik.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://inews.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://infobae.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://infogarut.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://infonasional.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://infoquest.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://inhnews.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://inikata.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://inilah.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://iniriau.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://inkl.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://inshorts.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://insidestategovernment.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://instagram.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://integritasnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://interest.co.nz/', 'Google', 3, 'Unofficial', 'Yes'),
('https://islandsbusiness.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://isranews.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://italiasette.it/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ittefaq.com.bd/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jagran.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jamill.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jantaserishta.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jateng.disway.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jatimtimes.com/', 'Google', 3, 'Official', 'No'),
('https://javedch.com/', 'Google', 3, 'Official', 'No'),
('https://jawaban.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jawapos.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jiemian.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jogja.tribunnews.com/', 'Google', 3, 'Official', 'No'),
('https://jogja.viva.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jogjapolitan.harianjogja.com/', 'Google', 3, 'Official', 'No'),
('https://joglojateng.com/', 'Google', 3, 'Unofficial', 'No'),
('https://joongboo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://js100.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://jtvmadiun.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://justthenews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kabarbanten.pikiran-rakyat.com/', 'Google', 3, 'Official', 'No'),
('https://kabarbanyuwangi.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kabarcirebon.pikiran-rakyat.com/', 'Google', 3, 'Official', 'No'),
('https://kabarhariini.id/', 'Google', 3, 'Unofficial', 'No'),
('https://kabarin.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kabarmadura.id/', 'Google', 3, 'Unofficial', 'No'),
('https://kabarmajalengka.pikiran-rakyat.com/', 'Google', 3, 'Official', 'No'),
('https://kabarpriangan.pikiran-rakyat.com/', 'Google', 3, 'Official', 'No'),
('https://kabulnow.com/', 'Google', 3, 'Official', 'No'),
('https://kalteng.antaranews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kaltim.antaranews.com/', 'Google', 3, 'Official', 'No'),
('https://kaltim.antaranews.com/berita/239053/dinkes-kaltim-catat-kasus-dbd-mencapai-2210-kasus', 'Google', 3, 'Official', 'No'),
('https://kaltim.tribunnews.com/', 'Google', 3, 'Official', 'No'),
('https://kaltimpost.jawapos.com/', 'Google', 3, 'Official', 'No'),
('https://kampucheathmey.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kanzhongguo.eu/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kaohoon.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://karar.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://karawangpost.pikiran-rakyat.com/', 'Google', 3, 'Official', 'No'),
('https://karpatalja.ma/', 'Google', 3, 'Official', 'No'),
('https://kathmandupost.com/', 'Google', 3, 'Official', 'No'),
('https://kdfnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kdhnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kdsn.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kemkes.go.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kenh14.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kepri.antaranews.com/', 'Google', 3, 'Official', 'No'),
('https://keralakaumudi.com/', 'Google', 3, 'Official', 'No'),
('https://kevesko.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kfdm.com/', 'Google', 3, 'Official', 'No'),
('https://kffhealthnews.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kh.cc-times.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://khabargaon.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://khaophuket.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://khaosod.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://khoahocdoisong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://khoahocphothong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://khonkaenlink.info/', 'Google', 3, 'Unofficial', 'Yes'),
('https://khq.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kidotalkradio.com/', 'Google', 3, 'Unofficial', 'No'),
('https://kienthuc.net.vn/', 'Google', 3, 'Official', 'No'),
('https://kilasjatim.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kingtop.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kinhte.congthuong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kinhtedothi.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kku.ac.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://knews.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://komchadluek.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kompas.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kompas.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kompas.tv/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kompasiana.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kookjeilbo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://koranmanado.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://koreajn.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://koreajoongangdaily.joins.com/', 'Google', 3, 'Official', 'No'),
('https://kosmo.com.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kpl.gov.la/', 'Chart', 12, 'Official', 'No'),
('https://krdo.com/', 'Google', 3, 'Official', 'No'),
('https://ksbtdanang.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ksmnews.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kstatecollegian.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ktok.iheart.com/', 'Google', 3, 'Unofficial', 'No'),
('https://kumparan.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kupang.tribunnews.com/', 'Google', 3, 'Official', 'No'),
('https://kwqc.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://kyeonggi.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://la1ere.franceinfo.fr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://la1ere.francetvinfo.fr/', 'Google', 3, 'Official', 'No'),
('https://ladbible.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lafune.eu/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lampost.co/', 'Google', 3, 'Official', 'No'),
('https://laodong.vn/', 'Google', 3, 'Official', 'No'),
('https://laodongthudo.vn/', 'Google', 3, 'Official', 'No'),
('https://latimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://leadership.ng/', 'Google', 3, 'Official', 'No'),
('https://lebak.inews.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://leho.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lesprosdelapetiteenfance.fr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://life.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lifestyle.bisnis.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lifestyle.sindonews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lifestyle.znews.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://linfo.re/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lingkar.news/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lintasgayo.co/', 'Google', 3, 'Unofficial', 'No'),
('https://liputan6.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://liputanoke.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://liramedia.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://litenews.hk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://livehindustan.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://livelaw.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://logos-pres.md/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lokmattimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lombokpost.jawapos.com/', 'Google', 3, 'Official', 'No'),
('https://luatvietnam.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://lvz.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.21jingji.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.antaranews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.economictimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.haberturk.com/', 'Google', 3, 'Official', 'No'),
('https://m.halloriau.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.hkej.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.phnompenhpost.com/', 'Google', 3, 'Official', 'No'),
('https://m.sohu.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.tf.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.thepaper.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://m.tribunnews.com/', 'Google', 3, 'Official', 'No'),
('https://macaudailytimes.com.mo/', 'Google', 3, 'Official', 'No'),
('https://magzter.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://majoriti.com.my/', 'Google', 3, 'Official', 'No'),
('https://makassar.antaranews.com/', 'Google', 3, 'Official', 'No'),
('https://makassar.tribunnews.com/', 'Google', 3, 'Official', 'No'),
('https://maklumat.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://malangtimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://malawi24.com/', 'Google', 3, 'Official', 'No'),
('https://malaymail.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://malaysia.news.yahoo.com/', 'Google', 3, 'Official', 'No'),
('https://malaysiagazette.com/', 'Google', 3, 'Official', 'No'),
('https://malaysiakini.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://malaysiatribune.news/', 'Google', 3, 'Unofficial', 'Yes'),
('https://manado.tribunnews.com/', 'Google', 3, 'Official', 'No'),
('https://mangish.net/', 'Google', 3, 'Unofficial', 'No'),
('https://manilastandard.net/', 'Google', 3, 'Official', 'No'),
('https://marketeeronline.co/', 'Google', 3, 'Unofficial', 'Yes'),
('https://marunadanmalayalee.com/', 'Google', 3, 'Official', 'No'),
('https://mashriqtv.pk/', 'Google', 3, 'Official', 'No'),
('https://matichon.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mb.com.ph/', 'Google', 3, 'Official', 'No'),
('https://mc-doualiya.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://medcom.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://media.chinhphu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mediacenter.riau.go.id/', 'Chart', 12, 'Official', 'No'),
('https://mediaindonesia.com/', 'Google', 3, 'Official', 'No'),
('https://mediarakata.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mediaselangor.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://medicaldoc.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://medicalrepublic.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://medicalxpress.com/', 'Google', 3, 'Official', 'No'),
('https://medquest.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://megapolitan.antaranews.com/', 'Google', 3, 'Official', 'No'),
('https://megapolitan.kompas.com/', 'Google', 3, 'Official', 'No'),
('https://menafn.com/', 'Google', 3, 'Official', 'No'),
('https://merahputih.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mercurynews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://merdeka.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://metro.batampos.co.id/', 'Google', 3, 'Official', 'No'),
('https://metropolis.batampos.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://metroriau.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://meyka.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mgorod.kz/', 'Google', 3, 'Official', 'No'),
('https://mgronline.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://minanews.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mindanaotimes.com.ph/', 'Google', 3, 'Official', 'No'),
('https://mindanews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://minews.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://minutemirror.com.pk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mirror.co.uk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mirrormedia.mg/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mistar.id/', 'Google', 3, 'Unofficial', 'No'),
('https://mitraauto.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mk.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mmnews.tv/', 'Google', 3, 'Official', 'No'),
('https://mmpeacemonitor.org/', 'Google', 3, 'Official', 'No'),
('https://mnnhanchinh.hanoi.edu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mobile.astroawani.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://moh.gov.bn/', 'Chart', 12, 'Official', 'No'),
('https://moh.gov.bn/news/situasi-terkini-jangkitan-covid-19-di-negara-brunei-darussalam/', 'Google', 3, 'Official', 'No'),
('https://moh.gov.kh/', 'Chart', 12, 'Official', 'No'),
('https://moitruong.net.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mommiesdaily.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://momsmoney.kontan.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://money.udn.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://more-news.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://morgenpost.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://motthegioi.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mrjjxw.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://multimedia.anamai.moph.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://munsifdaily.com/', 'Google', 3, 'Official', 'No'),
('https://mwnation.com/', 'Google', 3, 'Official', 'No'),
('https://myanmar-now.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mymotherlode.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mynbc15.com/', 'Google', 3, 'Official', 'No'),
('https://mynorthwest.com/', 'Google', 3, 'Official', 'No'),
('https://mypmp.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://mytvsuper.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://n.yam.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nagalandpost.com/', 'Google', 3, 'Official', 'No'),
('https://naidunia.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nambuccavalley.newsofthearea.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nasional.kompas.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://navbharatlive.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://navbharattimes.indiatimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nawabineka.com/', 'Google', 3, 'Unofficial', 'No'),
('https://nbd.com.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ndtv.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nefes.com.tr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://neoskosmos.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nepalipatro.com.np/', 'Google', 3, 'Unofficial', 'Yes'),
('https://netlife.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://neworleanscitybusiness.com/', 'Google', 3, 'Official', 'No'),
('https://news.az/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.bbsi.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.ch7.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.china.com.au/', 'Google', 3, 'Official', 'No'),
('https://news.china.com/', 'Google', 3, 'Official', 'No'),
('https://news.cnr.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.creaders.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.cts.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.detik.com/', 'Google', 3, 'Official', 'No'),
('https://news.detik.com/berita/d-7945491/kemenkes-deteksi-7-kasus-covid-19-di-indonesia', 'Google', 3, 'Official', 'No'),
('https://news.ebc.net.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.google.com/', 'Google', 3, 'Official', 'No'),
('https://news.harianjogja.com/', 'Google', 3, 'Official', 'No'),
('https://news.ipcf.org.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.livedoor.com/', 'Google', 3, 'Official', 'No'),
('https://news.ltn.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.nate.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.nextapple.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.ntv.co.jp/', 'Google', 3, 'Official', 'No'),
('https://news.pchome.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.pts.org.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.qq.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.rthk.hk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.sbs.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.ssbcrack.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.trueid.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.ttv.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.tuoitre.vn/', 'Google', 3, 'Official', 'No'),
('https://news.tvb.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news.webindia123.com/', 'Google', 3, 'Official', 'No'),
('https://news.yahoo.co.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news1.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news4nation.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news4teachers.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news8000.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://news9live.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newsaroma.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newscentral.africa/', 'Google', 3, 'Official', 'No'),
('https://newsclip.be/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newsflash.ph/', 'Google', 3, 'Unofficial', 'No'),
('https://newsgram.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newsinfo.inquirer.net/', 'Google', 3, 'Official', 'No'),
('https://newsis.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newskarnataka.com/', 'Google', 3, 'Official', 'No'),
('https://newsnasha.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newsnationtv.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newsofnepal.com/', 'Google', 3, 'Official', 'No'),
('https://newsonair.gov.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newsweekjapan.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newswise.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newswit.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newszoom.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newvision.co.ug/', 'Google', 3, 'Unofficial', 'Yes'),
('https://newzimbabwe.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ngaynay.vn/', 'Google', 3, 'Official', 'No'),
('https://nghean24h.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nguoi-noi-tieng.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nguoiduatin.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nguonluc.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nhachannuoi.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nhandan.vn/', 'Google', 3, 'Official', 'No'),
('https://nieuws.nl/', 'Google', 3, 'Official', 'No'),
('https://nigeriainfo.fm/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nikvesti.com/', 'Google', 3, 'Official', 'No'),
('https://nj.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nkytribune.com/', 'Google', 3, 'Official', 'No'),
('https://nld.com.vn/', 'Google', 3, 'Official', 'No'),
('https://nokorwatnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nongmin.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nongnghiephuuco.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nongnghiepmoitruong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nongsaeng.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://noovo.info/', 'Google', 3, 'Unofficial', 'Yes'),
('https://northeastnow.com/', 'Google', 3, 'Official', 'No'),
('https://nownews.seoul.co.kr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ntdtv.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ntnews.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ntvnews.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nusantara-news.co/', 'Google', 3, 'Unofficial', 'No'),
('https://nversia.ru/', 'Google', 3, 'Official', 'No'),
('https://nypost.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nytimes.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://nz.news.yahoo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://odh.ohio.gov/', 'Google', 3, 'Unofficial', 'Yes'),
('https://odishatv.in/', 'Google', 3, 'Official', 'No'),
('https://oklahoma.gov/', 'Chart', 12, 'Official', 'No'),
('https://omandaily.om/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ommcomnews.com/', 'Google', 3, 'Official', 'No'),
('https://onenewstvchannel.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://opb.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://opendata.ddc.moph.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://optometryadvisor.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://oregonlive.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://organiser.org/', 'Local News', 7, 'Official', 'No'),
('https://organizeindia.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://orientaldaily.com.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://osthessen-news.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ostsee-zeitung.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ottawacitizen.com/', 'Local News', 7, 'Official', 'No'),
('https://ottumwacourier.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://outbreaknewstoday.substack.com/', 'HTML', 8, 'Unofficial', 'No'),
('https://outlookindia.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://outsideonline.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ozgunkocaeli.com.tr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://pacificcross.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://padang.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://padek.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://pahami.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://palawan-news.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://paltv.disway.id/', 'Local News', 7, 'Official', 'No'),
('https://papuabarat.antaranews.com/', 'Official Government Sites', 4, 'Official', 'No'),
('https://passeportsante.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://patrolipost.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://pekanbaru.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://pentapostagma.gr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://peopledaily.digital/', 'Local News', 7, 'Unofficial', 'No'),
('https://peraknew.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://phim.health.gov.mw/', 'Official Government Sites', 4, 'Official', 'No'),
('https://phunuonline.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://phunuphapluat.nguoiduatin.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://phunutoday.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://phunuvietnam.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://pia.gov.ph/', 'Official Government Sites', 4, 'Official', 'No'),
('https://pisatoday.it/', 'Google', 3, 'Unofficial', 'Yes'),
('https://plo.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://pmnewsnigeria.com/', 'Local News', 7, 'Official', 'No'),
('https://policycircle.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://pontianak.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://pontianakpost.jawapos.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://portal.lviv.ua/', 'Local News', 7, 'Official', 'No'),
('https://portugalresident.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://positiveanglenews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://postkhmer.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://posttoday.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://pptvhd36.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://pr.moph.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://prahaar.in/', 'Local News', 7, 'Official', 'No'),
('https://prd.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://premiumtimesng.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://primamedia.ru/', 'Local News', 7, 'Official', 'No'),
('https://primo.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://probolinggokota.go.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://prohaba.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://promedmail.org/', 'HTML', 8, 'Official', 'No'),
('https://pronedra.ru/', 'Local News', 7, 'Unofficial', 'No'),
('https://prooren.ru/', 'Local News', 7, 'Unofficial', 'No'),
('https://pscd.prd.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://publications.aap.org/', 'JSON', 9, 'Official', 'No'),
('https://punchng.com/', 'Local News', 7, 'Official', 'No'),
('https://punto.com.ph/', 'Local News', 7, 'Unofficial', 'No'),
('https://qare.fr/', 'Google', 3, 'Unofficial', 'Yes'),
('https://qazinform.com/', 'Local News', 7, 'Official', 'No'),
('https://qna.org.qa/', 'Google', 3, 'Unofficial', 'Yes'),
('https://qnews.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://quadratin.com/', 'Local News', 7, 'Official', 'No'),
('https://quezoncity.gov.ph/', 'Official Government Sites', 4, 'Official', 'No'),
('https://radarbanjarmasin.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarbanyumas.disway.id/', 'Local News', 7, 'Official', 'No'),
('https://radarbengkulu.disway.id/', 'Local News', 7, 'Official', 'No'),
('https://radarbromo.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarjember.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarjogja.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarjogja.jawapos.com/jogja/656071866/potensi-demam-berdarah-dengue-dbd-meningkat-selama-kemarau-basah-dinkes-kota-jogja-hingga-mei-2025-sudah-ada-161-kasus', 'Google', 3, 'Official', 'No'),
('https://radarlamongan.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarmadiun.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarmalang.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarmojokerto.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radarsolo.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radartuban.jawapos.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://radartulungagung.jawapos.com/', 'Local News', 7, 'Official', 'No'),
('https://radioetoil.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://radyopilipinas.ph/', 'Official Government Sites', 4, 'Official', 'No'),
('https://rainews.it/', 'Google', 3, 'Unofficial', 'Yes'),
('https://rajexpress.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://raptorpersecutionuk.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://rata.lk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ratchaburi.prd.go.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://rbtv.disway.id/', 'Local News', 7, 'Official', 'No'),
('https://rctiplus.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://regional.espos.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://regional.kompas.com/', 'Local News', 7, 'Official', 'No'),
('https://regionriverina.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://rejabar.republika.co.id/', 'Local News', 7, 'Official', 'No'),
('https://rejogja.republika.co.id/', 'Local News', 7, 'Official', 'No'),
('https://reliefweb.int/', 'HTML', 8, 'Official', 'No'),
('https://remate.ph/', 'Local News', 7, 'Unofficial', 'No'),
('https://retractionwatch.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://riau.suara.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://riaueditor.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://risingnepaldaily.com/', 'Local News', 7, 'Official', 'No'),
('https://rmn.ph/', 'Local News', 7, 'Official', 'No'),
('https://rnz.co.nz/', 'Google', 3, 'Unofficial', 'Yes'),
('https://rollingstone.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ronggo.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://rpnradio.com/', 'Local News', 7, 'Official', 'No'),
('https://rri.co.id/', 'Official Government Sites', 4, 'Official', 'No'),
('https://ruangriau.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ruralradio.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ryt9.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://saba.ye/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sabahmedia.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://sanook.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://santafenewmexican.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sbs.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://scientificamerican.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://scooptw.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://secretchina.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sehatnegeriku.kemkes.go.id/', 'Official Government Sites', 4, 'Official', 'No'),
('https://setn.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sg.news.yahoo.com/', 'Local News', 7, 'Official', 'No'),
('https://shabiba.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://shafaq.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://sheridanmedia.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://shropshirelive.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://siakapkeli.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://siamnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://siamrath.co.th/', 'Local News', 7, 'Official', 'No'),
('https://sierraloaded.sl/', 'Local News', 7, 'Unofficial', 'No'),
('https://singtao.ca/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sinhala.asianmirror.lk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://smartraveller.gov.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://smartsumbar.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://smh.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://smninewschannel.com/', 'Local News', 7, 'Official', 'No'),
('https://sohuutritue.net.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://solo.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://solopos.espos.id/', 'Local News', 7, 'Official', 'No'),
('https://soloraya.harianjogja.com/', 'Local News', 7, 'Official', 'No'),
('https://sondhitalk.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://soyte.hanoi.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://soyte.tuyenquang.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://spectator.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://spiritriau.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://springnews.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://srilankamirror.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://steiermark.orf.at/', 'Local News', 7, 'Official', 'No'),
('https://stern.de/', 'Google', 3, 'Unofficial', 'Yes'),
('https://stratnewsglobal.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://stthomassource.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://suara.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://suarabaru.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://suarakalbar.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://suarantb.com/', 'Local News', 7, 'Official', 'No'),
('https://suarasurabaya.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://suckhoecong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://suckhoecongdongonline.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://suckhoedoisong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://suckhoemoitruong.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sudantribune.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sukabumiupdate.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sulsel.herald.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://sulteng.antaranews.com/', 'Official Government Sites', 4, 'Official', 'No'),
('https://sultramedia.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://sumatra.bisnis.com/', 'Local News', 7, 'Official', 'No'),
('https://sunmedia.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://surabaya.kompas.com/', 'Local News', 7, 'Official', 'No'),
('https://surabaya.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://surfcoastnews.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://suryamalang.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://sydney.edu.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://t.media/', 'Local News', 7, 'Unofficial', 'No'),
('https://taiwanhot.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://talk.ltn.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tamanhhospital.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tangselpos.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://taronews.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tass.ru/', 'Local News', 7, 'Official', 'No'),
('https://tatimes.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tatoli.tl/', 'Google', 3, 'Unofficial', 'Yes'),
('https://telanganatoday.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tengrinews.kz/', 'Local News', 7, 'Official', 'No'),
('https://ternate.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://texastribune.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://th.yanhee.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thaich8.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thainewsonline.co/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thaipbs.or.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thaipost.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thaipr.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thairath.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thanglong.chinhphu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thanhnien.vn/', 'Local News', 7, 'Official', 'No'),
('https://thanhtra.com.vn/', 'Official Government Sites', 4, 'Official', 'No'),
('https://thansettakij.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://theannapurnaexpress.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://theaustralian.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thebangkokinsight.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://theberkshireedge.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thechronicle.com.ph/', 'Local News', 7, 'Unofficial', 'No'),
('https://theconversation.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://theedgemalaysia.com/', 'Local News', 7, 'Official', 'No'),
('https://thegazellenews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thehawk.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thehealthsite.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://theindiadaily.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thelallantop.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thelucknowtribune.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://themandarin.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thenationonlineng.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thenewsmill.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thepaper.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thepatriot.in/', 'Local News', 7, 'Unofficial', 'No'),
('https://theprint.in/', 'Local News', 7, 'Official', 'No'),
('https://thesouthfirst.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://thestandard.co/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thestar.ng/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thesun.my/', 'Local News', 7, 'Official', 'No'),
('https://thethaiger.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://thethaovanhoa.vn/', 'Local News', 7, 'Official', 'No'),
('https://thewest.com.au/', 'Local News', 7, 'Official', 'No'),
('https://thewhistler.ng/', 'Local News', 7, 'Unofficial', 'No'),
('https://thiennhienmoitruong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thieunien.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thinkglobalhealth.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thisdaylive.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thuonghieucongluan.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://thuvienphapluat.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tiasang.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tiemchunglongchau.com.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tiengchuong.chinhphu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tiengiang.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tienphong.vn/', 'Local News', 7, 'Official', 'No'),
('https://tiin.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://timesindonesia.co.id/', 'Local News', 7, 'Official', 'No'),
('https://timesindonesia.co.id/peristiwa-daerah/540712/kasus-leptospirosis-naik-20-persen-dinkes-pacitan-anggarkan-rp2632-juta', 'Google', 3, 'Official', 'No'),
('https://timesofindia.indiatimes.com/', 'Local News', 7, 'Official', 'No'),
('https://timikaexpress.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://tnews.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tnnenglish.com/', 'Local News', 7, 'Official', 'No'),
('https://tnnthailand.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://today.az/', 'Google', 3, 'Unofficial', 'Yes'),
('https://today.line.me/', 'Google', 3, 'Unofficial', 'Yes'),
('https://todaygwangju.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://toonippo.co.jp/', 'Google', 3, 'Unofficial', 'Yes'),
('https://topick.hket.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://topnews.co.th/', 'Google', 3, 'Unofficial', 'Yes'),
('https://toronto.citynews.ca/', 'Local News', 7, 'Official', 'No'),
('https://travelhealthpro.org.uk/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tribratanews.jabar.polri.go.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tribune.com.pk/', 'Local News', 7, 'Official', 'No'),
('https://tribune.net.ph/', 'Local News', 7, 'Official', 'No'),
('https://tribuneindia.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tristarnews.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://trithucvn2.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://trt.global/', 'Local News', 7, 'Official', 'No'),
('https://tsargrad.tv/', 'Local News', 7, 'Unofficial', 'No'),
('https://ttbc-hcm.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ttt.hsnews.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ttv.com.tw/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tuoitre.vn/', 'Local News', 7, 'Official', 'No'),
('https://tuoitrenews.vn/', 'Local News', 7, 'Official', 'No'),
('https://tuoitrethudo.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://turnnewsapp.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tvonenews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tvsarawak.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://tw.news.yahoo.com/', 'Local News', 7, 'Official', 'No'),
('https://tw.nextapple.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://udn.com/', 'Local News', 7, 'Official', 'No'),
('https://uii.ac.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://uk.news.yahoo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://unair.ac.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://unb.com.bd/', 'Local News', 7, 'Official', 'No'),
('https://unicef.org.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://unn.ua/', 'Local News', 7, 'Official', 'No'),
('https://upi.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://urdu.app.com.pk/', 'Local News', 7, 'Official', 'No'),
('https://usatoday.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://utusan.com.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://v.daum.net/', 'Google', 3, 'Unofficial', 'Yes'),
('https://validnews.id/', 'Local News', 7, 'Official', 'No'),
('https://varnam.my/', 'Google', 3, 'Unofficial', 'Yes'),
('https://verdictum.in/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vietbao.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vietgiaitri.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://vietnambiz.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vietnamnet.vn/', 'Local News', 7, 'Official', 'No'),
('https://vietnamnews.vn/', 'Local News', 7, 'Official', 'No'),
('https://viettimes.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vigan.bomboradyo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://visayandailystar.com/', 'Local News', 7, 'Official', 'No'),
('https://visayas.politiko.com.ph/', 'Local News', 7, 'Unofficial', 'No'),
('https://viv.co.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vneconomy.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vnexpress.net/', 'Local News', 7, 'Official', 'No'),
('https://vnvc.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://voaindonesia.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://voh.com.vn/', 'Local News', 7, 'Official', 'No'),
('https://voi.id/', 'Local News', 7, 'Official', 'No'),
('https://vov.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vov.vn/', 'Local News', 7, 'Official', 'No'),
('https://vov1.vov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vovgiaothong.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://vtv.vn/', 'Local News', 7, 'Official', 'No'),
('https://wadr.org/', 'Local News', 7, 'Official', 'No'),
('https://wahpetondailynews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://warta.jogjakota.go.id/', 'Google', 3, 'Unofficial', 'Yes'),
('https://washingtonpost.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://watoday.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://waymagazine.org/', 'Google', 3, 'Unofficial', 'Yes'),
('https://wcvb.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://wdbj7.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://wenweipo.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://wenxuecity.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://wgntv.com/', 'Local News', 7, 'Official', 'No'),
('https://wien.orf.at/', 'Local News', 7, 'Official', 'No'),
('https://womensweekly.com.au/', 'Google', 3, 'Unofficial', 'Yes'),
('https://workpointnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://wusa9.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://wvnews.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://www.4ca.com.au/', 'Local News', 7, 'Official', 'No'),
('https://www.aa.com.tr/', 'Local News', 7, 'Official', 'No'),
('https://www.abante.com.ph/', 'Local News', 7, 'Official', 'No'),
('https://www.abc.net.au/', 'Local News', 7, 'Official', 'No'),
('https://www.abs-cbn.com/', 'Local News', 7, 'Official', 'No'),
('https://www.adaderana.lk/', 'Local News', 7, 'Official', 'No'),
('https://www.africanews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.agenzianova.com/', 'Local News', 7, 'Official', 'No'),
('https://www.ajnn.net/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.an17.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.antaranews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.antena3.com/', 'Local News', 7, 'Official', 'No'),
('https://www.aol.com/', 'Local News', 7, 'Official', 'No'),
('https://www.app.com.pk/', 'Local News', 7, 'Official', 'No'),
('https://www.arabnews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.atlantanewsfirst.com/', 'Local News', 7, 'Official', 'No'),
('https://www.audacy.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bag.admin.ch/', 'Local News', 7, 'Official', 'No'),
('https://www.balipost.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bangkokbiznews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bangkokpost.com/', 'Local News', 7, 'Official', 'No'),
('https://www.banglanews24.com/', 'Local News', 7, 'Official', 'No'),
('https://www.banglatribune.com/', 'Local News', 7, 'Official', 'No'),
('https://www.barrons.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bazonline.ch/', 'Local News', 7, 'Official', 'No'),
('https://www.bbc.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bd-pratidin.com/', 'Local News', 7, 'Official', 'No'),
('https://www.beritasatu.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bernama.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bernama.com/en/region/news.php?id=2428800', 'Google', 3, 'Unofficial', 'No'),
('https://www.bharian.com.my/', 'Local News', 7, 'Official', 'No'),
('https://www.bhaskar.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bhaskarhindi.com/', 'Local News', 7, 'Official', 'No'),
('https://www.birminghammail.co.uk/', 'Local News', 7, 'Official', 'No'),
('https://www.blackenterprise.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bloombergtechnoz.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bnionline.net/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.bolnews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.bovinevetonline.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.brantbeacon.ca/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.brecorder.com/', 'Local News', 7, 'Official', 'No'),
('https://www.brigadanews.ph/', 'Local News', 7, 'Official', 'No'),
('https://www.bssnews.net/', 'Local News', 7, 'Official', 'No'),
('https://www.busan.com/', 'Local News', 7, 'Official', 'No'),
('https://www.canada.ca/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.capitalfm.co.ke/', 'Local News', 7, 'Official', 'No'),
('https://www.caravan.kz/', 'Local News', 7, 'Official', 'No'),
('https://www.castlegarnews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.cbc.ca/', 'Local News', 7, 'Official', 'No'),
('https://www.cbs8.com/', 'Local News', 7, 'Official', 'No'),
('https://www.cbsnews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.cdc.gov.au/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.cdc.gov/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.cdcmoh.gov.kh/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.channel3000.com/', 'Local News', 7, 'Official', 'No'),
('https://www.channelnewsasia.com/', 'Local News', 7, 'Official', 'No'),
('https://www.chch.com/', 'Local News', 7, 'Official', 'No'),
('https://www.chiangraitimes.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.chronline.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.chugoku-np.co.jp/', 'Local News', 7, 'Official', 'No'),
('https://www.cidrap.umn.edu/', 'Local News', 7, 'Official', 'No'),
('https://www.citizen.co.za/', 'Local News', 7, 'Official', 'No'),
('https://www.cleveland.com/', 'Local News', 7, 'Official', 'No'),
('https://www.cna.com.tw/', 'Local News', 7, 'Official', 'No'),
('https://www.cnbcindonesia.com/', 'Facebook', 5, 'Official', 'No'),
('https://www.cnbcindonesia.com/lifestyle/20250531143853-33-637453/mendadak-kemenkes-keluarkan-peringatan-waspada-covid-19-ada-apa', 'Google', 3, 'Official', 'No'),
('https://www.cnnindonesia.com/', 'Local News', 7, 'Official', 'No'),
('https://www.congo-press.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.contagionlive.com/', 'Local News', 7, 'Official', 'No'),
('https://www.corsematin.com/', 'Local News', 7, 'Official', 'No'),
('https://www.cremonaoggi.it/', 'Local News', 7, 'Official', 'No'),
('https://www.ctvnews.ca/', 'Local News', 7, 'Official', 'No'),
('https://www.daijiworld.com/', 'Local News', 7, 'Official', 'No'),
('https://www.daily-sun.com/', 'Local News', 7, 'Official', 'No'),
('https://www.dailyexpress.com.my/', 'Local News', 7, 'Official', 'No'),
('https://www.dailymail.co.uk/', 'Local News', 7, 'Official', 'No'),
('https://www.dailymirror.lk/', 'Local News', 7, 'Official', 'No'),
('https://www.dailynews.lk/', 'Local News', 7, 'Official', 'No'),
('https://www.dawn.com/', 'Local News', 7, 'Official', 'No'),
('https://www.dawnnews.tv/', 'Local News', 7, 'Official', 'No'),
('https://www.deccanchronicle.com/', 'Local News', 7, 'Official', 'No'),
('https://www.deccanherald.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.denpost.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.denverpost.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.deshsewak.org/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.detik.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.dhakatribune.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.diariodeleon.es/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.diariosigloxxi.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.diarioveterinario.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.dimsumdaily.hk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.dshs.texas.gov/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.ecdc.europa.eu/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.ecr.co.za/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.elespanol.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.elperiodicodearagon.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.elprogreso.es/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.elsiglodetorreon.com.mx/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.endpolio.com.pk/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.ensonhaber.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.epochtimes.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.erienewsnow.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.ettoday.net/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.etvbharat.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.euronews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.express.co.uk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.facebook.com/', 'Facebook', 5, 'Unofficial', 'No'),
('https://www.fbcnews.com.fj/', 'Local News', 7, 'Official', 'No'),
('https://www.focusonafrica.info/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.forbes.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.fortuneindia.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.fox4news.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.franceinfo.fr/', 'Local News', 7, 'Official', 'No'),
('https://www.francetvinfo.fr/', 'Local News', 7, 'Official', 'No'),
('https://www.freemalaysiatoday.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.freep.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.fukuoka-now.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.galvnews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.gavi.org/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.gazeta.ru/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.gazzettadimantova.it/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.genpi.co/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.gmanetwork.com/news/topstories/nation/948110/doh-urges-public-to-fact-check-info-on-mpox/story/', 'Chart', 12, 'Official', 'No'),
('https://www.khmertimeskh.com/501691304/cambodia-reports-23-new-covid-19-cases/', 'Google', 3, 'Official', 'No'),
('https://www.mediafax.ro/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.medicalbrief.co.za/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.medicalnews.pk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.metrosouth.health.qld.gov.au/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.metrotvnews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.metrovaartha.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.millenniumpost.in/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.miragenews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.mk-mari.ru/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.mlive.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.modernghana.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.moh.gov.sg/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.moi.gov.mm/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.moroccoworldnews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.mrt.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.msn.com/', 'Chart', 12, 'Unofficial', 'No'),
('https://www.myanmaritv.com/', 'Local News', 7, 'Official', 'No'),
('https://www.myjoyonline.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.naewna.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nation.com.pk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nationthailand.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nbcchicago.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nbcdfw.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nbcnews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nbcrightnow.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.ndtv.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.ndtvprofit.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nea.gov.sg/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.newagebd.net/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.newindianexpress.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.newkerala.com/', 'Chart', 12, 'Unofficial', 'No'),
('https://www.newsbreak.com/', 'Chart', 12, 'Unofficial', 'No'),
('https://www.newsdrum.in/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.newsfirst.lk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.newsweek.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.newswire.lk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.newtimes.co.rw/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nicd.ac.za/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.nikkan-gendai.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nj.gov/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.njherald.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nlga.niedersachsen.de/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.nmhealth.org/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.nst.com.my/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nst.com.my/news/nation/2025/06/1225236/hfmd-surges-past-alert-level-johor-over-17500-cases', 'Google', 3, 'Official', 'No'),
('https://www.ntvbd.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nyasatimes.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.nzherald.co.nz/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.observerbd.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.ohmynews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.onmanorama.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.ozarksfirst.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.paho.org/', 'Google', 3, 'Official', 'No'),
('https://www.pakistantoday.com.pk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.panaynews.net/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.patrika.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.perthnow.com.au/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.philstar.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.pikiran-rakyat.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.plenglish.com/', 'Local News', 7, 'Official', 'No'),
('https://www.pna.gov.ph/', 'Local News', 7, 'Official', 'No'),
('https://www.portsmouth.co.uk/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.pravasiexpress.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.pressreader.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.prokerala.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.prpeak.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.pulse.com.gh/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.pulse.ug/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.qdnd.vn/', 'Local News', 7, 'Official', 'No'),
('https://www.queer.de/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.quintenews.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.radarbanten.co.id/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.radioguinee.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.rappler.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.reddeeradvocate.com/', 'Local News', 7, 'Unofficial', 'No'),
('https://www.reuters.com/', 'Local News', 7, 'Official', 'No'),
('https://www.riautelevisi.com/', 'Local News', 7, 'Official', 'No'),
('https://www.richmond-news.com/', 'Local News', 7, 'Official', 'No'),
('https://www.ringtimes.id/', 'Local News', 7, 'Official', 'No'),
('https://www.riosdenoticias.com.br/', 'Local News', 7, 'Official', 'No'),
('https://www.rri.co.id/', 'Local News', 7, 'Official', 'No'),
('https://www.rti.org.tw/', 'Local News', 7, 'Official', 'No'),
('https://www.rtl.nl/', 'Local News', 7, 'Official', 'No'),
('https://www.sacbee.com/', 'Local News', 7, 'Official', 'No'),
('https://www.salampapua.com/', 'Local News', 7, 'Official', 'No'),
('https://www.samoaobserver.ws/', 'Local News', 7, 'Official', 'No'),
('https://www.sanjuandailystar.com/', 'Local News', 7, 'Official', 'No'),
('https://www.sankei.com/', 'Local News', 7, 'Official', 'No'),
('https://www.savonanews.it/', 'Local News', 7, 'Official', 'No'),
('https://www.seattletimes.com/', 'Local News', 7, 'Official', 'No'),
('https://www.senenews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.sggp.org.vn/', 'Local News', 7, 'Official', 'No'),
('https://www.shawlocal.com/', 'Local News', 7, 'Official', 'No'),
('https://www.sinarharian.com.my/', 'Local News', 7, 'Official', 'No'),
('https://www.skipr.nl/', 'Local News', 7, 'Official', 'No'),
('https://www.socialnews.xyz/', 'Local News', 7, 'Official', 'No'),
('https://www.sowetanlive.co.za/', 'Local News', 7, 'Official', 'No'),
('https://www.stalbertgazette.com/', 'Local News', 7, 'Official', 'No'),
('https://www.standardmedia.co.ke/', 'Local News', 7, 'Official', 'No'),
('https://www.staradvertiser.com/', 'Local News', 7, 'Official', 'No'),
('https://www.stav.kp.ru/', 'Local News', 7, 'Official', 'No'),
('https://www.straitstimes.com/', 'Local News', 7, 'Official', 'No'),
('https://www.sunlive.co.nz/', 'Local News', 7, 'Official', 'No'),
('https://www.sunstar.com.ph/', 'Local News', 7, 'Official', 'No'),
('https://www.surinenglish.com/', 'Local News', 7, 'Official', 'No'),
('https://www.swindonadvertiser.co.uk/', 'Local News', 7, 'Official', 'No'),
('https://www.t-online.de/', 'Local News', 7, 'Official', 'No'),
('https://www.taiwannews.com.tw/', 'Local News', 7, 'Official', 'No'),
('https://www.tbsnews.net/', 'Local News', 7, 'Official', 'No'),
('https://www.telegraph.co.uk/', 'Local News', 7, 'Official', 'No'),
('https://www.teleprensa.com/', 'Local News', 7, 'Official', 'No'),
('https://www.tempo.co/', 'Local News', 7, 'Official', 'No'),
('https://www.tempostretto.it/', 'Local News', 7, 'Official', 'No'),
('https://www.the-star.co.ke/', 'Local News', 7, 'Official', 'No'),
('https://www.theage.com.au/', 'Local News', 7, 'Official', 'No'),
('https://www.theborneopost.com/', 'Local News', 7, 'Official', 'No'),
('https://www.thecanadianpressnews.ca/', 'Local News', 7, 'Official', 'No'),
('https://www.thecitizen.co.tz/', 'Local News', 7, 'Official', 'No'),
('https://www.thegoan.net/', 'Local News', 7, 'Official', 'No'),
('https://www.theguardian.com/', 'Local News', 7, 'Official', 'No'),
('https://www.thehindu.com/', 'Local News', 7, 'Official', 'No'),
('https://www.thenews.com.pk/', 'Local News', 7, 'Official', 'No'),
('https://www.theportugalnews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.thestar.com.my/', 'Local News', 7, 'Official', 'No'),
('https://www.thestar.com/', 'Local News', 7, 'Official', 'No'),
('https://www.thestatesman.com/', 'Local News', 7, 'Official', 'No'),
('https://www.theweek.in/', 'Local News', 7, 'Official', 'No'),
('https://www.timesnownews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.timesofisrael.com/', 'Local News', 7, 'Official', 'No'),
('https://www.timesunion.com/', 'Local News', 7, 'Official', 'No'),
('https://www.tintahijau.com/', 'Local News', 7, 'Official', 'No'),
('https://www.tl7.fr/', 'Local News', 7, 'Official', 'No'),
('https://www.tn.gov/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.tokyo-np.co.jp/', 'Local News', 7, 'Official', 'No'),
('https://www.tpr.org/', 'Local News', 7, 'Official', 'No'),
('https://www.travelandtourworld.com/', 'Local News', 7, 'Official', 'No'),
('https://www.tribunnews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.trt.global/', 'Local News', 7, 'Official', 'No'),
('https://www.umy.ac.id/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.unb.com.bd/', 'Local News', 7, 'Official', 'No'),
('https://www.uniindia.com/', 'Local News', 7, 'Official', 'No'),
('https://www.unmc.edu/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.usnews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.valleycentral.com/', 'Local News', 7, 'Official', 'No'),
('https://www.vax-before-travel.com/', 'HTML', 8, 'Official', 'No'),
('https://www.vietnam.vn/', 'Local News', 7, 'Official', 'No'),
('https://www.vietnamplus.vn/', 'Google', 3, 'Official', 'No'),
('https://www.viva.co.id/', 'Local News', 7, 'Official', 'No'),
('https://www.volgograd.kp.ru/', 'Local News', 7, 'Official', 'No'),
('https://www.wbaltv.com/', 'Local News', 7, 'Official', 'No'),
('https://www.wect.com/', 'Local News', 7, 'Official', 'No'),
('https://www.who.int/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www.wimberleyview.com/', 'Local News', 7, 'Official', 'No'),
('https://www.winnipegfreepress.com/', 'Local News', 7, 'Official', 'No'),
('https://www.witn.com/', 'Local News', 7, 'Official', 'No'),
('https://www.wkrn.com/', 'Local News', 7, 'Official', 'No'),
('https://www.wsws.org/', 'Local News', 7, 'Official', 'No'),
('https://www.wzzm13.com/', 'Local News', 7, 'Official', 'No'),
('https://www.xaluannews.com/', 'Local News', 7, 'Official', 'No'),
('https://www.yahoo.com/', 'Local News', 7, 'Official', 'No'),
('https://www.ygeiamou.gr/', 'Local News', 7, 'Official', 'No'),
('https://www.yna.co.kr/', 'Local News', 7, 'Official', 'No'),
('https://www.yomiuri.co.jp/', 'Local News', 7, 'Official', 'No'),
('https://www.yorkshirepost.co.uk/', 'Local News', 7, 'Official', 'No'),
('https://www.yourerie.com/', 'Local News', 7, 'Official', 'No'),
('https://www.zigzagweekly.net/', 'Local News', 7, 'Official', 'No'),
('https://www1.racgp.org.au/', 'Official Government Sites', 4, 'Official', 'No'),
('https://www3.nhk.or.jp/', 'Local News', 7, 'Official', 'No'),
('https://xaydungchinhsach.chinhphu.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://xinwen.bjd.com.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://xmnn.cn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://xn----ctbfecatgqygb5apl.xn--p1ai/', 'Google', 3, 'Unofficial', 'Yes'),
('https://yalovagazetesi.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://yeeyi.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://yicai.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://yogyakarta.kompas.com/', 'Local News', 7, 'Official', 'No'),
('https://yte.daklak.gov.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://ytemienbac.vn/', 'Google', 3, 'Unofficial', 'Yes'),
('https://zaochenbao.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://zaxid.net/', 'Local News', 7, 'Official', 'No'),
('https://zazoom.it/', 'Google', 3, 'Unofficial', 'Yes'),
('https://zeenews.india.com/', 'Google', 3, 'Unofficial', 'Yes'),
('https://znews.vn/', 'Google', 3, 'Unofficial', 'Yes');

UPDATE collector_sources s
SET
    config = COALESCE(s.config, '{}'::jsonb) || jsonb_strip_nulls(jsonb_build_object(
        'catalog_type', c.catalog_type,
        'catalog_type_id', c.type_id,
        'validity_status', c.validity_status,
        'from_engine', c.from_engine,
        'source_origin', CASE LOWER(c.from_engine)
            WHEN 'no' THEN 'Main Source'
            WHEN 'yes' THEN 'Other Source'
            ELSE NULL
        END,
        'source_catalog', 'ABVC Master Source'
    )),
    source_type = CASE
        WHEN LOWER(c.catalog_type) = 'facebook'
             AND LOWER(COALESCE(s.config->>'url', c.source_url)) LIKE '%facebook.com%'
            THEN 'social_media'
        ELSE s.source_type
    END,
    updated_at = NOW()
FROM abvc_catalog c
WHERE LOWER(RTRIM(COALESCE(s.config->>'url', ''), '/')) = LOWER(RTRIM(c.source_url, '/'));

COMMIT;
