-- Extend the existing language_markers master into the shared NLP lexicon.
-- Do not create a second nlp_lexicon table: existing language markers and
-- new metric/temporal terms use the same reviewed registry.

ALTER TABLE language_markers
    ADD COLUMN IF NOT EXISTS marker_type VARCHAR(40) NOT NULL DEFAULT 'language_marker',
    ADD COLUMN IF NOT EXISTS canonical_value TEXT,
    ADD COLUMN IF NOT EXISTS script VARCHAR(32),
    ADD COLUMN IF NOT EXISTS priority INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    ADD COLUMN IF NOT EXISTS source VARCHAR(40) NOT NULL DEFAULT 'curated';

DROP INDEX IF EXISTS idx_lang_markers_word_lang;
CREATE UNIQUE INDEX IF NOT EXISTS idx_lang_markers_word_lang_type
    ON language_markers(word, language, marker_type);
CREATE INDEX IF NOT EXISTS idx_lang_markers_type_language
    ON language_markers(marker_type, language) WHERE is_active = TRUE;

-- Existing language detection rows remain language_marker rows. The terms
-- below are the former code lexicon, now editable and reloadable from DB.
INSERT INTO language_markers
    (word, language, marker_type, canonical_value, script, priority, source)
VALUES
    ('case', 'en', 'metric_case', 'cases', 'Latin', 10, 'legacy_migrated'),
    ('cases', 'en', 'metric_case', 'cases', 'Latin', 10, 'legacy_migrated'),
    ('ca', 'vi', 'metric_case', 'cases', 'Latin', 5, 'legacy_migrated'),
    ('infection', 'en', 'metric_case', 'cases', 'Latin', 20, 'legacy_migrated'),
    ('infections', 'en', 'metric_case', 'cases', 'Latin', 20, 'legacy_migrated'),
    ('patient', 'en', 'metric_case', 'cases', 'Latin', 30, 'legacy_migrated'),
    ('patients', 'en', 'metric_case', 'cases', 'Latin', 30, 'legacy_migrated'),
    ('kasus', 'id', 'metric_case', 'cases', 'Latin', 10, 'legacy_migrated'),
    ('infeksi', 'id', 'metric_case', 'cases', 'Latin', 20, 'legacy_migrated'),
    ('infection', 'id', 'metric_case', 'cases', 'Latin', 20, 'legacy_migrated'),
    ('infections', 'id', 'metric_case', 'cases', 'Latin', 20, 'legacy_migrated'),
    ('kes', 'ms', 'metric_case', 'cases', 'Latin', 10, 'legacy_migrated'),
    ('ca', 'ms', 'metric_case', 'cases', 'Latin', 5, 'legacy_migrated'),
    ('ca mắc', 'vi', 'metric_case', 'cases', 'Latin', 10, 'legacy_migrated'),
    ('ca nhiễm', 'vi', 'metric_case', 'cases', 'Latin', 10, 'legacy_migrated'),
    ('trường hợp', 'vi', 'metric_case', 'cases', 'Latin', 20, 'legacy_migrated'),
    ('bệnh nhân', 'vi', 'metric_case', 'cases', 'Latin', 30, 'legacy_migrated'),
    ('ผู้ป่วย', 'th', 'metric_case', 'cases', 'Thai', 10, 'legacy_migrated'),
    ('ติดเชื้อ', 'th', 'metric_case', 'cases', 'Thai', 20, 'legacy_migrated'),
    ('ราย', 'th', 'metric_case', 'cases', 'Thai', 30, 'legacy_migrated'),
    ('กรณี', 'th', 'metric_case', 'cases', 'Thai', 40, 'legacy_migrated'),
    ('ករណី', 'km', 'metric_case', 'cases', 'Khmer', 10, 'legacy_migrated'),
    ('អ្នកឆ្លង', 'km', 'metric_case', 'cases', 'Khmer', 20, 'legacy_migrated'),
    ('ກໍລະນີ', 'lo', 'metric_case', 'cases', 'Lao', 10, 'legacy_migrated'),
    ('ກໍລະນີສະສົມ', 'lo', 'metric_case', 'cases', 'Lao', 20, 'legacy_migrated'),
    ('ຄົນເຈັບ', 'lo', 'metric_case', 'cases', 'Lao', 30, 'legacy_migrated'),
    ('ຜູ້ຕິດເຊື້ອ', 'lo', 'metric_case', 'cases', 'Lao', 40, 'legacy_migrated'),
    ('လူနာ', 'my', 'metric_case', 'cases', 'Myanmar', 10, 'legacy_migrated'),
    ('ကူးစက်သူ', 'my', 'metric_case', 'cases', 'Myanmar', 20, 'legacy_migrated'),
    ('ဦး', 'my', 'metric_case', 'cases', 'Myanmar', 30, 'legacy_migrated'),
    ('kaso', 'tl', 'metric_case', 'cases', 'Latin', 10, 'legacy_migrated'),
    ('pasyente', 'tl', 'metric_case', 'cases', 'Latin', 20, 'legacy_migrated'),
    ('death', 'en', 'metric_death', 'deaths', 'Latin', 10, 'legacy_migrated'),
    ('deaths', 'en', 'metric_death', 'deaths', 'Latin', 10, 'legacy_migrated'),
    ('death toll', 'en', 'metric_death', 'deaths', 'Latin', 10, 'legacy_migrated'),
    ('fatalities', 'en', 'metric_death', 'deaths', 'Latin', 20, 'legacy_migrated'),
    ('died', 'en', 'metric_death', 'deaths', 'Latin', 20, 'legacy_migrated'),
    ('kematian', 'id', 'metric_death', 'deaths', 'Latin', 10, 'legacy_migrated'),
    ('meninggal', 'id', 'metric_death', 'deaths', 'Latin', 20, 'legacy_migrated'),
    ('meninggal dunia', 'id', 'metric_death', 'deaths', 'Latin', 20, 'legacy_migrated'),
    ('tewas', 'id', 'metric_death', 'deaths', 'Latin', 30, 'legacy_migrated'),
    ('korban jiwa', 'id', 'metric_death', 'deaths', 'Latin', 30, 'legacy_migrated'),
    ('tử vong', 'vi', 'metric_death', 'deaths', 'Latin', 10, 'legacy_migrated'),
    ('ผู้เสียชีวิต', 'th', 'metric_death', 'deaths', 'Thai', 10, 'legacy_migrated'),
    ('เสียชีวิต', 'th', 'metric_death', 'deaths', 'Thai', 10, 'legacy_migrated'),
    ('ស្លាប់', 'km', 'metric_death', 'deaths', 'Khmer', 10, 'legacy_migrated'),
    ('ເສຍຊີວິດ', 'lo', 'metric_death', 'deaths', 'Lao', 10, 'legacy_migrated'),
    ('သေဆုံး', 'my', 'metric_death', 'deaths', 'Myanmar', 10, 'legacy_migrated'),
    ('kamatayan', 'tl', 'metric_death', 'deaths', 'Latin', 10, 'legacy_migrated'),
    ('ราย', 'th', 'count_unit', 'person', 'Thai', 10, 'legacy_migrated'),
    ('คน', 'th', 'count_unit', 'person', 'Thai', 10, 'legacy_migrated'),
    ('orang', 'id', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('orang', 'ms', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('people', 'en', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('person', 'en', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('januari', 'id', 'temporal_month', '1', 'Latin', 10, 'legacy_migrated'),
    ('februari', 'id', 'temporal_month', '2', 'Latin', 10, 'legacy_migrated'),
    ('maret', 'id', 'temporal_month', '3', 'Latin', 10, 'legacy_migrated'),
    ('april', 'id', 'temporal_month', '4', 'Latin', 10, 'legacy_migrated'),
    ('mei', 'id', 'temporal_month', '5', 'Latin', 10, 'legacy_migrated'),
    ('juni', 'id', 'temporal_month', '6', 'Latin', 10, 'legacy_migrated'),
    ('juli', 'id', 'temporal_month', '7', 'Latin', 10, 'legacy_migrated'),
    ('agustus', 'id', 'temporal_month', '8', 'Latin', 10, 'legacy_migrated'),
    ('september', 'id', 'temporal_month', '9', 'Latin', 10, 'legacy_migrated'),
    ('oktober', 'id', 'temporal_month', '10', 'Latin', 10, 'legacy_migrated'),
    ('november', 'id', 'temporal_month', '11', 'Latin', 10, 'legacy_migrated'),
    ('desember', 'id', 'temporal_month', '12', 'Latin', 10, 'legacy_migrated'),
    ('january', 'en', 'temporal_month', '1', 'Latin', 10, 'legacy_migrated'),
    ('february', 'en', 'temporal_month', '2', 'Latin', 10, 'legacy_migrated'),
    ('march', 'en', 'temporal_month', '3', 'Latin', 10, 'legacy_migrated'),
    ('may', 'en', 'temporal_month', '5', 'Latin', 10, 'legacy_migrated'),
    ('june', 'en', 'temporal_month', '6', 'Latin', 10, 'legacy_migrated'),
    ('july', 'en', 'temporal_month', '7', 'Latin', 10, 'legacy_migrated'),
    ('august', 'en', 'temporal_month', '8', 'Latin', 10, 'legacy_migrated'),
    ('october', 'en', 'temporal_month', '10', 'Latin', 10, 'legacy_migrated'),
    ('december', 'en', 'temporal_month', '12', 'Latin', 10, 'legacy_migrated'),
    ('januari', 'ms', 'temporal_month', '1', 'Latin', 10, 'legacy_migrated'),
    ('februari', 'ms', 'temporal_month', '2', 'Latin', 10, 'legacy_migrated'),
    ('mac', 'ms', 'temporal_month', '3', 'Latin', 10, 'legacy_migrated'),
    ('mei', 'ms', 'temporal_month', '5', 'Latin', 10, 'legacy_migrated'),
    ('julai', 'ms', 'temporal_month', '7', 'Latin', 10, 'legacy_migrated'),
    ('ogos', 'ms', 'temporal_month', '8', 'Latin', 10, 'legacy_migrated'),
    ('disember', 'ms', 'temporal_month', '12', 'Latin', 10, 'legacy_migrated'),
    ('Enero', 'tl', 'temporal_month', '1', 'Latin', 10, 'legacy_migrated'),
    ('Pebrero', 'tl', 'temporal_month', '2', 'Latin', 10, 'legacy_migrated'),
    ('Marso', 'tl', 'temporal_month', '3', 'Latin', 10, 'legacy_migrated'),
    ('Abril', 'tl', 'temporal_month', '4', 'Latin', 10, 'legacy_migrated'),
    ('Mayo', 'tl', 'temporal_month', '5', 'Latin', 10, 'legacy_migrated'),
    ('Hunyo', 'tl', 'temporal_month', '6', 'Latin', 10, 'legacy_migrated'),
    ('Hulyo', 'tl', 'temporal_month', '7', 'Latin', 10, 'legacy_migrated'),
    ('Agosto', 'tl', 'temporal_month', '8', 'Latin', 10, 'legacy_migrated'),
    ('Setyembre', 'tl', 'temporal_month', '9', 'Latin', 10, 'legacy_migrated'),
    ('Oktubre', 'tl', 'temporal_month', '10', 'Latin', 10, 'legacy_migrated'),
    ('Nobyembre', 'tl', 'temporal_month', '11', 'Latin', 10, 'legacy_migrated'),
    ('Disyembre', 'tl', 'temporal_month', '12', 'Latin', 10, 'legacy_migrated'),
    ('april', 'en', 'temporal_month', '4', 'Latin', 10, 'legacy_migrated'),
    ('september', 'en', 'temporal_month', '9', 'Latin', 10, 'legacy_migrated'),
    ('november', 'en', 'temporal_month', '11', 'Latin', 10, 'legacy_migrated'),
    ('jan', 'en', 'temporal_month', '1', 'Latin', 20, 'legacy_migrated'),
    ('feb', 'en', 'temporal_month', '2', 'Latin', 20, 'legacy_migrated'),
    ('mar', 'en', 'temporal_month', '3', 'Latin', 20, 'legacy_migrated'),
    ('apr', 'en', 'temporal_month', '4', 'Latin', 20, 'legacy_migrated'),
    ('jun', 'en', 'temporal_month', '6', 'Latin', 20, 'legacy_migrated'),
    ('jul', 'en', 'temporal_month', '7', 'Latin', 20, 'legacy_migrated'),
    ('aug', 'en', 'temporal_month', '8', 'Latin', 20, 'legacy_migrated'),
    ('sep', 'en', 'temporal_month', '9', 'Latin', 20, 'legacy_migrated'),
    ('oct', 'en', 'temporal_month', '10', 'Latin', 20, 'legacy_migrated'),
    ('nov', 'en', 'temporal_month', '11', 'Latin', 20, 'legacy_migrated'),
    ('dec', 'en', 'temporal_month', '12', 'Latin', 20, 'legacy_migrated'),
    ('agst', 'id', 'temporal_month', '8', 'Latin', 20, 'legacy_migrated'),
    ('ags', 'id', 'temporal_month', '8', 'Latin', 20, 'legacy_migrated'),
    ('agu', 'id', 'temporal_month', '8', 'Latin', 20, 'legacy_migrated'),
    ('okt', 'id', 'temporal_month', '10', 'Latin', 20, 'legacy_migrated'),
    ('des', 'id', 'temporal_month', '12', 'Latin', 20, 'legacy_migrated'),
    ('jan', 'id', 'temporal_month', '1', 'Latin', 20, 'legacy_migrated'),
    ('feb', 'id', 'temporal_month', '2', 'Latin', 20, 'legacy_migrated'),
    ('mar', 'id', 'temporal_month', '3', 'Latin', 20, 'legacy_migrated'),
    ('apr', 'id', 'temporal_month', '4', 'Latin', 20, 'legacy_migrated'),
    ('jun', 'id', 'temporal_month', '6', 'Latin', 20, 'legacy_migrated'),
    ('jul', 'id', 'temporal_month', '7', 'Latin', 20, 'legacy_migrated'),
    ('sep', 'id', 'temporal_month', '9', 'Latin', 20, 'legacy_migrated'),
    ('nov', 'id', 'temporal_month', '11', 'Latin', 20, 'legacy_migrated'),
    ('dis', 'id', 'temporal_month', '12', 'Latin', 20, 'legacy_migrated'),
    ('april', 'ms', 'temporal_month', '4', 'Latin', 10, 'legacy_migrated'),
    ('jun', 'ms', 'temporal_month', '6', 'Latin', 10, 'legacy_migrated'),
    ('september', 'ms', 'temporal_month', '9', 'Latin', 10, 'legacy_migrated'),
    ('oktober', 'ms', 'temporal_month', '10', 'Latin', 10, 'legacy_migrated'),
    ('november', 'ms', 'temporal_month', '11', 'Latin', 10, 'legacy_migrated'),
    ('tháng một', 'vi', 'temporal_month', '1', 'Latin', 10, 'legacy_migrated'),
    ('tháng hai', 'vi', 'temporal_month', '2', 'Latin', 10, 'legacy_migrated'),
    ('tháng ba', 'vi', 'temporal_month', '3', 'Latin', 10, 'legacy_migrated'),
    ('tháng tư', 'vi', 'temporal_month', '4', 'Latin', 10, 'legacy_migrated'),
    ('tháng năm', 'vi', 'temporal_month', '5', 'Latin', 10, 'legacy_migrated'),
    ('tháng sáu', 'vi', 'temporal_month', '6', 'Latin', 10, 'legacy_migrated'),
    ('tháng bảy', 'vi', 'temporal_month', '7', 'Latin', 10, 'legacy_migrated'),
    ('tháng tám', 'vi', 'temporal_month', '8', 'Latin', 10, 'legacy_migrated'),
    ('tháng chín', 'vi', 'temporal_month', '9', 'Latin', 10, 'legacy_migrated'),
    ('tháng mười', 'vi', 'temporal_month', '10', 'Latin', 10, 'legacy_migrated'),
    ('tháng mười một', 'vi', 'temporal_month', '11', 'Latin', 10, 'legacy_migrated'),
    ('tháng mười hai', 'vi', 'temporal_month', '12', 'Latin', 10, 'legacy_migrated'),
    ('มกราคม', 'th', 'temporal_month', '1', 'Thai', 10, 'legacy_migrated'),
    ('กุมภาพันธ์', 'th', 'temporal_month', '2', 'Thai', 10, 'legacy_migrated'),
    ('มีนาคม', 'th', 'temporal_month', '3', 'Thai', 10, 'legacy_migrated'),
    ('เมษายน', 'th', 'temporal_month', '4', 'Thai', 10, 'legacy_migrated'),
    ('พฤษภาคม', 'th', 'temporal_month', '5', 'Thai', 10, 'legacy_migrated'),
    ('มิถุนายน', 'th', 'temporal_month', '6', 'Thai', 10, 'legacy_migrated'),
    ('กรกฎาคม', 'th', 'temporal_month', '7', 'Thai', 10, 'legacy_migrated'),
    ('สิงหาคม', 'th', 'temporal_month', '8', 'Thai', 10, 'legacy_migrated'),
    ('กันยายน', 'th', 'temporal_month', '9', 'Thai', 10, 'legacy_migrated'),
    ('ตุลาคม', 'th', 'temporal_month', '10', 'Thai', 10, 'legacy_migrated'),
    ('พฤศจิกายน', 'th', 'temporal_month', '11', 'Thai', 10, 'legacy_migrated'),
    ('ธันวาคม', 'th', 'temporal_month', '12', 'Thai', 10, 'legacy_migrated'),
    ('ខែមករា', 'km', 'temporal_month', '1', 'Khmer', 10, 'legacy_migrated'),
    ('ខែកុម្ភៈ', 'km', 'temporal_month', '2', 'Khmer', 10, 'legacy_migrated'),
    ('ខែមីនា', 'km', 'temporal_month', '3', 'Khmer', 10, 'legacy_migrated'),
    ('ខែមេសា', 'km', 'temporal_month', '4', 'Khmer', 10, 'legacy_migrated'),
    ('ខែឧសភា', 'km', 'temporal_month', '5', 'Khmer', 10, 'legacy_migrated'),
    ('ខែមិថុនា', 'km', 'temporal_month', '6', 'Khmer', 10, 'legacy_migrated'),
    ('ខែកក្កដា', 'km', 'temporal_month', '7', 'Khmer', 10, 'legacy_migrated'),
    ('ខែសីហា', 'km', 'temporal_month', '8', 'Khmer', 10, 'legacy_migrated'),
    ('ខែកញ្ញា', 'km', 'temporal_month', '9', 'Khmer', 10, 'legacy_migrated'),
    ('ខែតុលា', 'km', 'temporal_month', '10', 'Khmer', 10, 'legacy_migrated'),
    ('ខែវិច្ឆិកា', 'km', 'temporal_month', '11', 'Khmer', 10, 'legacy_migrated'),
    ('ខែធ្នូ', 'km', 'temporal_month', '12', 'Khmer', 10, 'legacy_migrated'),
    ('ມັງກອນ', 'lo', 'temporal_month', '1', 'Lao', 10, 'legacy_migrated'),
    ('ກຸມພາ', 'lo', 'temporal_month', '2', 'Lao', 10, 'legacy_migrated'),
    ('ມີນາ', 'lo', 'temporal_month', '3', 'Lao', 10, 'legacy_migrated'),
    ('ເມສາ', 'lo', 'temporal_month', '4', 'Lao', 10, 'legacy_migrated'),
    ('ພຶດສະພາ', 'lo', 'temporal_month', '5', 'Lao', 10, 'legacy_migrated'),
    ('ມິຖຸນາ', 'lo', 'temporal_month', '6', 'Lao', 10, 'legacy_migrated'),
    ('ກໍລະກົດ', 'lo', 'temporal_month', '7', 'Lao', 10, 'legacy_migrated'),
    ('ສິງຫາ', 'lo', 'temporal_month', '8', 'Lao', 10, 'legacy_migrated'),
    ('ກັນຍາ', 'lo', 'temporal_month', '9', 'Lao', 10, 'legacy_migrated'),
    ('ຕຸລາ', 'lo', 'temporal_month', '10', 'Lao', 10, 'legacy_migrated'),
    ('ພະຈິກ', 'lo', 'temporal_month', '11', 'Lao', 10, 'legacy_migrated'),
    ('ທັນວາ', 'lo', 'temporal_month', '12', 'Lao', 10, 'legacy_migrated'),
    ('ဇန်နဝါရီ', 'my', 'temporal_month', '1', 'Myanmar', 10, 'legacy_migrated'),
    ('ဖေဖော်ဝါရီ', 'my', 'temporal_month', '2', 'Myanmar', 10, 'legacy_migrated'),
    ('မတ်', 'my', 'temporal_month', '3', 'Myanmar', 10, 'legacy_migrated'),
    ('ဧပြီ', 'my', 'temporal_month', '4', 'Myanmar', 10, 'legacy_migrated'),
    ('မေ', 'my', 'temporal_month', '5', 'Myanmar', 10, 'legacy_migrated'),
    ('ဇွန်', 'my', 'temporal_month', '6', 'Myanmar', 10, 'legacy_migrated'),
    ('ဇူလိုင်', 'my', 'temporal_month', '7', 'Myanmar', 10, 'legacy_migrated'),
    ('သြဂုတ်', 'my', 'temporal_month', '8', 'Myanmar', 10, 'legacy_migrated'),
    ('စက်တင်ဘာ', 'my', 'temporal_month', '9', 'Myanmar', 10, 'legacy_migrated'),
    ('အောက်တိုဘာ', 'my', 'temporal_month', '10', 'Myanmar', 10, 'legacy_migrated'),
    ('နိုဝင်ဘာ', 'my', 'temporal_month', '11', 'Myanmar', 10, 'legacy_migrated'),
    ('ဒီဇင်ဘာ', 'my', 'temporal_month', '12', 'Myanmar', 10, 'legacy_migrated')
ON CONFLICT (word, language, marker_type) DO UPDATE
SET canonical_value = EXCLUDED.canonical_value,
    script = EXCLUDED.script,
    priority = EXCLUDED.priority,
    is_active = TRUE,
    updated_at = NOW();

-- Count-unit vocabulary is kept in the same registry so metric parsing never
-- needs a second hardcoded list.
INSERT INTO language_markers
    (word, language, marker_type, canonical_value, script, priority, source)
VALUES
    ('case', 'en', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('cases', 'en', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('patient', 'en', 'count_unit', 'person', 'Latin', 20, 'legacy_migrated'),
    ('patients', 'en', 'count_unit', 'person', 'Latin', 20, 'legacy_migrated'),
    ('kasus', 'id', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('pasien', 'id', 'count_unit', 'person', 'Latin', 20, 'legacy_migrated'),
    ('kes', 'ms', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('pasien', 'ms', 'count_unit', 'person', 'Latin', 20, 'legacy_migrated'),
    ('ca', 'vi', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('trường hợp', 'vi', 'count_unit', 'person', 'Latin', 20, 'legacy_migrated'),
    ('នាក់', 'km', 'count_unit', 'person', 'Khmer', 10, 'legacy_migrated'),
    ('ຄົນ', 'lo', 'count_unit', 'person', 'Lao', 10, 'legacy_migrated'),
    ('ဦး', 'my', 'count_unit', 'person', 'Myanmar', 10, 'legacy_migrated'),
    ('ယောက်', 'my', 'count_unit', 'person', 'Myanmar', 20, 'legacy_migrated'),
    ('kaso', 'tl', 'count_unit', 'person', 'Latin', 10, 'legacy_migrated'),
    ('pasyente', 'tl', 'count_unit', 'person', 'Latin', 20, 'legacy_migrated')
ON CONFLICT (word, language, marker_type) DO UPDATE
SET canonical_value = EXCLUDED.canonical_value,
    script = EXCLUDED.script,
    priority = EXCLUDED.priority,
    is_active = TRUE,
    updated_at = NOW();

-- Disease terms belong in nlp_keywords/disease_aliases, not in the metric
-- lexicon. These are reviewed multilingual aliases rather than article text
-- scraped blindly into the master data.
INSERT INTO nlp_keywords (category, keyword, target_label, is_active, priority)
VALUES
    ('disease', 'demam denggi', 'DBD', TRUE, 3),
    ('disease', 'demam campak', 'MEASLES', TRUE, 3),
    ('disease', 'ไข้เลือดออก', 'DBD', TRUE, 3),
    ('disease', 'ໄຂ້ເລືອດອອກ', 'DBD', TRUE, 3),
    ('disease', 'ໄຂ້ຍຸງ', 'malaria', TRUE, 3),
    ('disease', 'ພະຍາດຫັດ', 'MEASLES', TRUE, 3),
    ('disease', 'ໄຂ້ຫວັດໃຫຍ່', 'INFLUENZA', TRUE, 3),
    ('disease', 'ໝາບ້າ', 'RABIES', TRUE, 3),
    ('disease', 'trangkaso', 'INFLUENZA', TRUE, 3),
    ('disease', 'tigdas', 'MEASLES', TRUE, 3),
    ('disease', 'dengue', 'DBD', TRUE, 3),
    ('disease', 'sốt xuất huyết', 'DBD', TRUE, 3)
ON CONFLICT (category, keyword) DO UPDATE
SET target_label = EXCLUDED.target_label,
    is_active = TRUE,
    priority = LEAST(nlp_keywords.priority, EXCLUDED.priority),
    updated_at = NOW();
