-- Move the remaining country aliases out of Python constants. Location and
-- country mentions now use the same location_aliases master.
WITH aliases(alias_name, canonical_name, language) AS (
    VALUES
    ('brunei', 'Brunei', 'en'),
    ('brunei darussalam', 'Brunei', 'en'),
    ('cambodia', 'Cambodia', 'en'),
    ('kampuchea', 'Cambodia', 'en'),
    ('indonesia', 'Indonesia', 'en'),
    ('laos', 'Laos', 'en'),
    ('lao pdr', 'Laos', 'en'),
    ('lao people''s democratic republic', 'Laos', 'en'),
    ('lao people s democratic republic', 'Laos', 'en'),
    ('malaysia', 'Malaysia', 'en'),
    ('myanmar', 'Myanmar', 'en'),
    ('burma', 'Myanmar', 'en'),
    ('philippines', 'Philippines', 'en'),
    ('the philippines', 'Philippines', 'en'),
    ('philippine', 'Philippines', 'en'),
    ('singapore', 'Singapore', 'en'),
    ('singapura', 'Singapore', 'en'),
    ('ประเทศไทย', 'Thailand', 'th'),
    ('กម្ពុជា', 'Cambodia', 'km'),
    ('မြန်မာ', 'Myanmar', 'my'),
    ('ລາວ', 'Laos', 'lo'),
    ('ສປປ ລາວ', 'Laos', 'lo'),
    ('ສປປລາວ', 'Laos', 'lo'),
    ('việt nam', 'Vietnam', 'vi'),
    ('s''pore', 'Singapore', 'en'),
    ('kamboja', 'Cambodia', 'id'),
    ('cambodian', 'Cambodia', 'en'),
    ('vietnamese', 'Vietnam', 'en'),
    ('indonesian', 'Indonesia', 'en'),
    ('malaysian', 'Malaysia', 'en'),
    ('filipino', 'Philippines', 'en'),
    ('filipina', 'Philippines', 'id'),
    ('thailand', 'Thailand', 'en'),
    ('timor-leste', 'Timor-Leste', 'en'),
    ('timor leste', 'Timor-Leste', 'en'),
    ('east timor', 'Timor-Leste', 'en'),
    ('vietnam', 'Vietnam', 'en'),
    ('viet nam', 'Vietnam', 'en'),
    ('south sudan', 'South Sudan', 'en'),
    ('sudan', 'Sudan', 'en'),
    ('democratic republic of the congo', 'Democratic Republic of the Congo', 'en'),
    ('dr congo', 'Democratic Republic of the Congo', 'en'),
    ('rd congo', 'Democratic Republic of the Congo', 'en'),
    ('rd kongo', 'Democratic Republic of the Congo', 'en'),
    ('congo', 'Democratic Republic of the Congo', 'en'),
    ('kongo', 'Democratic Republic of the Congo', 'en'),
    ('united states of america', 'United States', 'en'),
    ('united states', 'United States', 'en'),
    ('u.s.a.', 'United States', 'en'),
    ('u.s.', 'United States', 'en'),
    ('usa', 'United States', 'en'),
    ('us', 'United States', 'en'),
    ('amerika serikat', 'United States', 'id'),
    ('mexico', 'Mexico', 'en'),
    ('meksiko', 'Mexico', 'id'),
    ('canada', 'Canada', 'en'),
    ('kanada', 'Canada', 'id'),
    ('brazil', 'Brazil', 'en'),
    ('brasil', 'Brazil', 'id'),
    ('united kingdom', 'United Kingdom', 'en'),
    ('uk', 'United Kingdom', 'en'),
    ('britain', 'United Kingdom', 'en'),
    ('great britain', 'United Kingdom', 'en'),
    ('inggris', 'United Kingdom', 'id'),
    ('germany', 'Germany', 'en'),
    ('jerman', 'Germany', 'id'),
    ('france', 'France', 'en'),
    ('prancis', 'France', 'id'),
    ('spain', 'Spain', 'en'),
    ('spanyol', 'Spain', 'id'),
    ('italy', 'Italy', 'en'),
    ('italia', 'Italy', 'id'),
    ('russia', 'Russia', 'en'),
    ('rusia', 'Russia', 'id'),
    ('china', 'China', 'en'),
    ('tiongkok', 'China', 'id'),
    ('india', 'India', 'en'),
    ('japan', 'Japan', 'en'),
    ('jepang', 'Japan', 'id'),
    ('south korea', 'South Korea', 'en'),
    ('korea selatan', 'South Korea', 'id'),
    ('australia', 'Australia', 'en'),
    ('new zealand', 'New Zealand', 'en'),
    ('pakistan', 'Pakistan', 'en'),
    ('bangladesh', 'Bangladesh', 'en'),
    ('nigeria', 'Nigeria', 'en'),
    ('south africa', 'South Africa', 'en'),
    ('egypt', 'Egypt', 'en'),
    ('saudi arabia', 'Saudi Arabia', 'en')
)
INSERT INTO location_aliases (location_id, alias_name, language, is_preferred)
SELECT l.id, a.alias_name, a.language, FALSE
FROM aliases a
JOIN locations l
  ON LOWER(l.name) = LOWER(a.canonical_name)
 AND LOWER(l.country) = LOWER(a.canonical_name)
ON CONFLICT (location_id, alias_name, language) DO NOTHING;
