-- Complete the reviewed disease vocabulary that was previously embedded in
-- the extractor. The database is now the editable source for these aliases.
INSERT INTO nlp_keywords (category, keyword, target_label, priority, is_active, updated_at)
VALUES
    ('disease', 'anthrax', 'Anthrax', 350, TRUE, NOW()),
    ('disease', 'ari', 'Acute Respiratory Infection (ARI/ISPA)', 350, TRUE, NOW()),
    ('disease', 'breakbone fever', 'DBD', 350, TRUE, NOW()),
    ('disease', 'bệnh lao', 'Tuberculosis', 350, TRUE, NOW()),
    ('disease', 'bệnh sốt xuất huyết', 'Dengue', 350, TRUE, NOW()),
    ('disease', 'bệnh thương hàn', 'Typhoid fever', 350, TRUE, NOW()),
    ('disease', 'bệnh tả', 'Cholera', 350, TRUE, NOW()),
    ('disease', 'bệnh đậu mùa khỉ', 'MPOX', 350, TRUE, NOW()),
    ('disease', 'cancer', 'Cancer', 350, TRUE, NOW()),
    ('disease', 'cholera', 'Cholera', 350, TRUE, NOW()),
    ('disease', 'clade 1b', 'Mpox', 350, TRUE, NOW()),
    ('disease', 'clade ib', 'Mpox', 350, TRUE, NOW()),
    ('disease', 'coronavirus', 'COVID-19', 350, TRUE, NOW()),
    ('disease', 'cvdpv', 'Poliomyelitis', 350, TRUE, NOW()),
    ('disease', 'cvdpv2', 'Poliomyelitis', 350, TRUE, NOW()),
    ('disease', 'dau mua khi', 'MPOX', 350, TRUE, NOW()),
    ('disease', 'demam tifoid', 'Typhoid fever', 350, TRUE, NOW()),
    ('disease', 'dengue fever', 'DBD', 350, TRUE, NOW()),
    ('disease', 'dengue haemorrhagic fever', 'DBD', 350, TRUE, NOW()),
    ('disease', 'dengue hemorrhagic fever', 'DBD', 350, TRUE, NOW()),
    ('disease', 'diabetes', 'Diabetes mellitus', 350, TRUE, NOW()),
    ('disease', 'diabetes melitus', 'Diabetes mellitus', 350, TRUE, NOW()),
    ('disease', 'diare', 'Acute diarrhea', 350, TRUE, NOW()),
    ('disease', 'diarrhea', 'Acute diarrhea', 350, TRUE, NOW()),
    ('disease', 'diarrhoea', 'Acute diarrhea', 350, TRUE, NOW()),
    ('disease', 'ebola virus', 'Ebola disease, virus unspecified', 350, TRUE, NOW()),
    ('disease', 'ebola virus disease', 'Ebola disease, virus unspecified', 350, TRUE, NOW()),
    ('disease', 'evd', 'Ebola disease, virus unspecified', 350, TRUE, NOW()),
    ('disease', 'haemorrhagic fever', 'DBD', 350, TRUE, NOW()),
    ('disease', 'hand foot mouth disease', 'HFMD', 350, TRUE, NOW()),
    ('disease', 'hand, foot and mouth disease', 'HFMD', 350, TRUE, NOW()),
    ('disease', 'heart attack', 'Heart attack', 350, TRUE, NOW()),
    ('disease', 'hemorrhagic fever', 'DBD', 350, TRUE, NOW()),
    ('disease', 'hipertensi', 'Hypertension', 350, TRUE, NOW()),
    ('disease', 'hypertension', 'Hypertension', 350, TRUE, NOW()),
    ('disease', 'infeksi saluran pernafasan akut', 'Acute Respiratory Infection (ARI/ISPA)', 350, TRUE, NOW()),
    ('disease', 'infeksi saluran pernapasan akut', 'Acute Respiratory Infection (ARI/ISPA)', 350, TRUE, NOW()),
    ('disease', 'kudis', 'Scabies', 350, TRUE, NOW()),
    ('disease', 'lepra', 'Leprosy', 350, TRUE, NOW()),
    ('disease', 'lower respiratory infection', 'Acute Respiratory Infection (ARI/ISPA)', 350, TRUE, NOW()),
    ('disease', 'nipah virus', 'Nipah virus disease', 350, TRUE, NOW()),
    ('disease', 'penyakit anjing gila', 'Rabies', 350, TRUE, NOW()),
    ('disease', 'penyakit ebola', 'Ebola disease, virus unspecified', 350, TRUE, NOW()),
    ('disease', 'penyakit jantung koroner', 'Coronary heart disease', 350, TRUE, NOW()),
    ('disease', 'penyakit virus ebola', 'Ebola disease, virus unspecified', 350, TRUE, NOW()),
    ('disease', 'pertusis', 'Pertussis', 350, TRUE, NOW()),
    ('disease', 'poliomyelitis', 'Poliomyelitis', 350, TRUE, NOW()),
    ('disease', 'poliovirus', 'Poliomyelitis', 350, TRUE, NOW()),
    ('disease', 'radang paru', 'Pneumonia', 350, TRUE, NOW()),
    ('disease', 'radang paru-paru', 'Pneumonia', 350, TRUE, NOW()),
    ('disease', 'respiratory syncytial', 'Respiratory syncytial virus infection', 350, TRUE, NOW()),
    ('disease', 'respiratory syncytial virus', 'Respiratory syncytial virus infection', 350, TRUE, NOW()),
    ('disease', 'rsv', 'Respiratory syncytial virus infection', 350, TRUE, NOW()),
    ('disease', 'scabies', 'Scabies', 350, TRUE, NOW()),
    ('disease', 'swine flu', 'flu babi', 350, TRUE, NOW()),
    ('disease', 'sốt xuất huyết dengue', 'Dengue', 350, TRUE, NOW()),
    ('disease', 'tipes', 'Typhoid fever', 350, TRUE, NOW()),
    ('disease', 'typhoid', 'Typhoid fever', 350, TRUE, NOW()),
    ('disease', 'typhoid fever', 'Typhoid fever', 350, TRUE, NOW()),
    ('disease', 'upper respiratory infection', 'Acute Respiratory Infection (ARI/ISPA)', 350, TRUE, NOW()),
    ('disease', 'virus ebola', 'Ebola disease, virus unspecified', 350, TRUE, NOW()),
    ('disease', 'viêm phổi', 'Pneumonia', 350, TRUE, NOW()),
    ('disease', 'ท้องร่วง', 'Acute diarrhea', 350, TRUE, NOW()),
    ('disease', 'ปอดบวม', 'Pneumonia', 350, TRUE, NOW()),
    ('disease', 'พิษสุนัขบ้า', 'Rabies', 350, TRUE, NOW()),
    ('disease', 'มะเร็ง', 'Cancer', 350, TRUE, NOW()),
    ('disease', 'หัวใจวาย', 'Heart attack', 350, TRUE, NOW()),
    ('disease', 'เอ็มพ็อกซ์', 'MPOX', 350, TRUE, NOW()),
    ('disease', 'โควิด', 'COVID-19', 350, TRUE, NOW()),
    ('disease', 'โควิด-19', 'COVID-19', 350, TRUE, NOW()),
    ('disease', 'โรคเอ็มพ็อกซ์', 'MPOX', 350, TRUE, NOW()),
    ('disease', 'ไข้ชิคุนกุนยา', 'Chikungunya', 350, TRUE, NOW()),
    ('disease', 'ไข้หวัดใหญ่', 'Influenza', 350, TRUE, NOW()),
    ('disease', 'ไข้เด็งกี', 'Dengue', 350, TRUE, NOW()),
    ('disease', 'ໄຂ້ຍຸງລາຍ', 'Dengue', 350, TRUE, NOW())
ON CONFLICT (category, keyword) DO UPDATE SET
    target_label = EXCLUDED.target_label,
    is_active = TRUE,
    priority = LEAST(nlp_keywords.priority, EXCLUDED.priority),
    updated_at = NOW();
