-- Word-number tokens are editable lexicon data, not extractor constants.
INSERT INTO language_markers
    (word, language, marker_type, canonical_value, script, priority, source)
VALUES
    ('one','en','number_word','1','Latin',10,'legacy_migrated'),
    ('two','en','number_word','2','Latin',10,'legacy_migrated'),
    ('three','en','number_word','3','Latin',10,'legacy_migrated'),
    ('four','en','number_word','4','Latin',10,'legacy_migrated'),
    ('five','en','number_word','5','Latin',10,'legacy_migrated'),
    ('six','en','number_word','6','Latin',10,'legacy_migrated'),
    ('seven','en','number_word','7','Latin',10,'legacy_migrated'),
    ('eight','en','number_word','8','Latin',10,'legacy_migrated'),
    ('nine','en','number_word','9','Latin',10,'legacy_migrated'),
    ('ten','en','number_word','10','Latin',10,'legacy_migrated'),
    ('eleven','en','number_word','11','Latin',10,'legacy_migrated'),
    ('twelve','en','number_word','12','Latin',10,'legacy_migrated'),
    ('thirteen','en','number_word','13','Latin',10,'legacy_migrated'),
    ('fourteen','en','number_word','14','Latin',10,'legacy_migrated'),
    ('fifteen','en','number_word','15','Latin',10,'legacy_migrated'),
    ('sixteen','en','number_word','16','Latin',10,'legacy_migrated'),
    ('seventeen','en','number_word','17','Latin',10,'legacy_migrated'),
    ('eighteen','en','number_word','18','Latin',10,'legacy_migrated'),
    ('nineteen','en','number_word','19','Latin',10,'legacy_migrated'),
    ('twenty','en','number_word','20','Latin',10,'legacy_migrated'),
    ('thirty','en','number_word','30','Latin',10,'legacy_migrated'),
    ('forty','en','number_word','40','Latin',10,'legacy_migrated'),
    ('fifty','en','number_word','50','Latin',10,'legacy_migrated'),
    ('sixty','en','number_word','60','Latin',10,'legacy_migrated'),
    ('seventy','en','number_word','70','Latin',10,'legacy_migrated'),
    ('eighty','en','number_word','80','Latin',10,'legacy_migrated'),
    ('ninety','en','number_word','90','Latin',10,'legacy_migrated'),
    ('hundred','en','number_word','100','Latin',10,'legacy_migrated'),
    ('a hundred','en','number_word','100','Latin',10,'legacy_migrated'),
    ('a dozen','en','number_word','12','Latin',10,'legacy_migrated'),
    ('twenty-one','en','number_word','21','Latin',20,'legacy_migrated'),
    ('twenty-two','en','number_word','22','Latin',20,'legacy_migrated'),
    ('twenty-three','en','number_word','23','Latin',20,'legacy_migrated'),
    ('twenty-four','en','number_word','24','Latin',20,'legacy_migrated'),
    ('twenty-five','en','number_word','25','Latin',20,'legacy_migrated'),
    ('twenty-six','en','number_word','26','Latin',20,'legacy_migrated'),
    ('twenty-seven','en','number_word','27','Latin',20,'legacy_migrated'),
    ('twenty-eight','en','number_word','28','Latin',20,'legacy_migrated'),
    ('twenty-nine','en','number_word','29','Latin',20,'legacy_migrated'),
    ('satu','id','number_word','1','Latin',10,'legacy_migrated'),
    ('dua','id','number_word','2','Latin',10,'legacy_migrated'),
    ('tiga','id','number_word','3','Latin',10,'legacy_migrated'),
    ('empat','id','number_word','4','Latin',10,'legacy_migrated'),
    ('lima','id','number_word','5','Latin',10,'legacy_migrated'),
    ('enam','id','number_word','6','Latin',10,'legacy_migrated'),
    ('tujuh','id','number_word','7','Latin',10,'legacy_migrated'),
    ('delapan','id','number_word','8','Latin',10,'legacy_migrated'),
    ('sembilan','id','number_word','9','Latin',10,'legacy_migrated'),
    ('sepuluh','id','number_word','10','Latin',10,'legacy_migrated'),
    ('sebelas','id','number_word','11','Latin',10,'legacy_migrated'),
    ('dua belas','id','number_word','12','Latin',10,'legacy_migrated'),
    ('tiga belas','id','number_word','13','Latin',10,'legacy_migrated'),
    ('empat belas','id','number_word','14','Latin',10,'legacy_migrated'),
    ('lima belas','id','number_word','15','Latin',10,'legacy_migrated'),
    ('enam belas','id','number_word','16','Latin',10,'legacy_migrated'),
    ('tujuh belas','id','number_word','17','Latin',10,'legacy_migrated'),
    ('delapan belas','id','number_word','18','Latin',10,'legacy_migrated'),
    ('sembilan belas','id','number_word','19','Latin',10,'legacy_migrated'),
    ('dua puluh','id','number_word','20','Latin',10,'legacy_migrated'),
    ('tiga puluh','id','number_word','30','Latin',10,'legacy_migrated'),
    ('empat puluh','id','number_word','40','Latin',10,'legacy_migrated'),
    ('lima puluh','id','number_word','50','Latin',10,'legacy_migrated'),
    ('enam puluh','id','number_word','60','Latin',10,'legacy_migrated'),
    ('tujuh puluh','id','number_word','70','Latin',10,'legacy_migrated'),
    ('delapan puluh','id','number_word','80','Latin',10,'legacy_migrated'),
    ('sembilan puluh','id','number_word','90','Latin',10,'legacy_migrated'),
    ('seratus','id','number_word','100','Latin',10,'legacy_migrated'),
    ('seribu','id','number_word','1000','Latin',10,'legacy_migrated'),
    ('seorang','id','number_word','1','Latin',20,'legacy_migrated'),
    ('seekor','id','number_word','1','Latin',20,'legacy_migrated'),
    ('sepasang','id','number_word','2','Latin',20,'legacy_migrated'),
    ('kedua','id','number_word','2','Latin',20,'legacy_migrated'),
    ('tiga bersaudara','id','number_word','3','Latin',20,'legacy_migrated'),
    ('một','vi','number_word','1','Latin',10,'legacy_migrated'),
    ('hai','vi','number_word','2','Latin',10,'legacy_migrated'),
    ('ba','vi','number_word','3','Latin',10,'legacy_migrated'),
    ('bốn','vi','number_word','4','Latin',10,'legacy_migrated'),
    ('năm','vi','number_word','5','Latin',10,'legacy_migrated'),
    ('sáu','vi','number_word','6','Latin',10,'legacy_migrated'),
    ('bảy','vi','number_word','7','Latin',10,'legacy_migrated'),
    ('tám','vi','number_word','8','Latin',10,'legacy_migrated'),
    ('chín','vi','number_word','9','Latin',10,'legacy_migrated'),
    ('mười','vi','number_word','10','Latin',10,'legacy_migrated'),
    ('mười một','vi','number_word','11','Latin',10,'legacy_migrated'),
    ('mười hai','vi','number_word','12','Latin',10,'legacy_migrated'),
    ('hai mươi','vi','number_word','20','Latin',10,'legacy_migrated'),
    ('ba mươi','vi','number_word','30','Latin',10,'legacy_migrated'),
    ('một trăm','vi','number_word','100','Latin',10,'legacy_migrated'),
    ('một người','vi','number_word','1','Latin',20,'legacy_migrated'),
    ('một ca','vi','number_word','1','Latin',20,'legacy_migrated'),
    ('một bệnh nhân','vi','number_word','1','Latin',20,'legacy_migrated'),
    ('hai mẹ con','vi','number_word','2','Latin',20,'legacy_migrated'),
    ('cả hai','vi','number_word','2','Latin',20,'legacy_migrated'),
    ('หนึ่ง','th','number_word','1','Thai',10,'legacy_migrated'),
    ('สอง','th','number_word','2','Thai',10,'legacy_migrated'),
    ('สาม','th','number_word','3','Thai',10,'legacy_migrated'),
    ('สี่','th','number_word','4','Thai',10,'legacy_migrated'),
    ('ห้า','th','number_word','5','Thai',10,'legacy_migrated'),
    ('หก','th','number_word','6','Thai',10,'legacy_migrated'),
    ('เจ็ด','th','number_word','7','Thai',10,'legacy_migrated'),
    ('แปด','th','number_word','8','Thai',10,'legacy_migrated'),
    ('เก้า','th','number_word','9','Thai',10,'legacy_migrated'),
    ('สิบ','th','number_word','10','Thai',10,'legacy_migrated'),
    ('ยี่สิบ','th','number_word','20','Thai',10,'legacy_migrated'),
    ('สามสิบ','th','number_word','30','Thai',10,'legacy_migrated'),
    ('หนึ่งร้อย','th','number_word','100','Thai',10,'legacy_migrated'),
    ('ร้อย','th','number_word','100','Thai',10,'legacy_migrated'),
    ('รายหนึ่ง','th','number_word','1','Thai',20,'legacy_migrated'),
    ('ทั้งสองราย','th','number_word','2','Thai',20,'legacy_migrated')
ON CONFLICT (word, language, marker_type) DO UPDATE SET
    canonical_value = EXCLUDED.canonical_value,
    is_active = TRUE,
    updated_at = NOW();
