apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlp-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: nlp-dev-nlp-root-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: dev.abvc-surveillance.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: disease-backend-rust
                port:
                  number: 8081
          - path: /nlp
            pathType: Prefix
            backend:
              service:
                name: disease-frontend-next
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: disease-frontend-next
                port:
                  number: 3000
