apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: nlp-models}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources: {requests: {storage: 12Gi}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: collector-social-media}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources: {requests: {storage: 4Gi}}
