#!/usr/bin/env python3
"""Import bencana_ai_live articles into an isolated historical NLP queue.

The source database contains disaster events, while this project trains a
disease classifier.  Therefore only the raw article plus safe source metadata
is copied; disease labels are generated by this project's NLP pipeline.

The importer is idempotent through an object_path marker and never publishes
to the production disease.raw queue unless the caller explicitly overrides
the queue name.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
from urllib.parse import urlsplit, urlunsplit

import pika
import psycopg
from psycopg.rows import dict_row


LOG = logging.getLogger("import_bencana_ai_live")
DEFAULT_QUEUE = "disease.history.bencana_ai_live"
MARKER_PREFIX = "import:bencana_ai_live:"


def derive_source_url(target_url: str) -> str:
    """Reuse target credentials/host while selecting the restored source DB."""
    parsed = urlsplit(target_url)
    path = "/bencana_ai_live"
    return urlunsplit((parsed.scheme, parsed.netloc, path, parsed.query, parsed.fragment))


def args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-database-url",
        default=os.getenv("BENCANA_AI_LIVE_DATABASE_URL"),
        help="Source PostgreSQL URL; defaults to DATABASE_URL with database bencana_ai_live.",
    )
    parser.add_argument(
        "--target-database-url",
        default=os.getenv("DATABASE_URL"),
        help="Target disease_ai PostgreSQL URL (default: DATABASE_URL).",
    )
    parser.add_argument("--rabbitmq-url", default=os.getenv("RABBITMQ_URL"))
    parser.add_argument("--queue", default=DEFAULT_QUEUE)
    parser.add_argument("--limit", type=int, default=0, help="Import at most N rows; 0 means all.")
    parser.add_argument(
        "--health-only-source",
        action="store_true",
        help="Select only source events likely related to disease/epidemic/poisoning.",
    )
    parser.add_argument(
        "--republish-existing",
        action="store_true",
        help="Publish already imported rows again (useful after queue purge).",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--no-publish",
        action="store_true",
        help="Insert rows as NEW but do not publish queue messages.",
    )
    return parser.parse_args()


def source_rows(conn, health_only: bool = False):
    health_clause = ""
    if health_only:
        health_clause = """
          AND EXISTS (
              SELECT 1
              FROM events disease_event
              WHERE disease_event.raw_report_id = r.id
                AND lower(coalesce(disease_event.event_type, '')) ~
                    '(disease|epidem|wabah|penyakit|poison|keracunan)'
          )
        """
    return conn.execute(
        f"""
        SELECT r.id, r.source_type, r.source_name, r.published_at,
               r.original_text, r.url, r.object_path,
               COALESCE(e.language, '') AS source_language,
               COALESCE(e.country, '') AS source_country
        FROM raw_reports r
        LEFT JOIN LATERAL (
            SELECT language, country
            FROM events
            WHERE raw_report_id = r.id
            ORDER BY confidence DESC NULLS LAST, created_at DESC
            LIMIT 1
        ) e ON TRUE
        WHERE r.original_text IS NOT NULL
          AND length(btrim(r.original_text)) > 20
          {health_clause}
        ORDER BY r.created_at, r.id
        """
    ).fetchall()


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    config = args()
    target_url = config.target_database_url or os.getenv("TRAINING_DATABASE_URL")
    if not target_url:
        raise SystemExit("DATABASE_URL atau --target-database-url wajib diisi")
    source_url = config.source_database_url or derive_source_url(target_url)

    with psycopg.connect(source_url, row_factory=dict_row) as source:
        rows = source_rows(source, config.health_only_source)
    if config.limit > 0:
        rows = rows[: config.limit]

    LOG.info("Source rows eligible: %d", len(rows))
    if config.dry_run:
        return 0

    imported = 0
    skipped = 0
    messages: list[tuple[str, dict]] = []
    with psycopg.connect(target_url, row_factory=dict_row) as target:
        for row in rows:
            marker = f"{MARKER_PREFIX}{row['id']}"
            existing = target.execute(
                "SELECT id, source_type, source_name, published_at, original_text, url, processing_status FROM raw_reports WHERE object_path=%s LIMIT 1",
                (marker,),
            ).fetchone()
            if existing:
                skipped += 1
                if not config.republish_existing:
                    continue
                if existing["processing_status"] != "NEW":
                    continue
                raw_id = str(existing["id"])
                target_row = existing
            else:
                inserted = target.execute(
                    """
                    INSERT INTO raw_reports
                        (source_type, source_name, published_at, original_text, url,
                         object_path, processing_status)
                    VALUES (%s, %s, %s, %s, %s, %s, 'NEW')
                    RETURNING id
                    """,
                    (
                        row["source_type"] or "imported",
                        row["source_name"] or "bencana_ai_live",
                        row["published_at"],
                        row["original_text"],
                        row["url"],
                        marker,
                    ),
                ).fetchone()
                raw_id = str(inserted["id"])
                target_row = row

            messages.append(
                (
                    raw_id,
                    {
                        "raw_report_id": raw_id,
                        "source_type": target_row["source_type"] or "imported",
                        "source_name": target_row["source_name"] or "bencana_ai_live",
                        "published_at": target_row["published_at"].isoformat() if target_row["published_at"] else "",
                        "text": target_row["original_text"],
                        "url": target_row["url"],
                        "object_path": marker,
                        "source_language": row["source_language"] or "",
                        "source_country": row["source_country"] or "",
                    },
                )
            )
            imported += 1
            if imported % 500 == 0:
                target.commit()
                LOG.info("Inserted %d rows", imported)
        target.commit()

    published = 0
    if not config.no_publish:
        rabbitmq_url = config.rabbitmq_url or os.getenv("RABBITMQ_URL")
        if not rabbitmq_url:
            raise SystemExit("RABBITMQ_URL atau --rabbitmq-url wajib diisi untuk publish")
        connection = pika.BlockingConnection(pika.URLParameters(rabbitmq_url))
        channel = connection.channel()
        channel.queue_declare(queue=config.queue, durable=True)
        for _, message in messages:
            channel.basic_publish(
                exchange="",
                routing_key=config.queue,
                body=json.dumps(message, ensure_ascii=False).encode("utf-8"),
                properties=pika.BasicProperties(
                    delivery_mode=2,
                    content_type="application/json",
                ),
            )
            published += 1
        connection.close()

    LOG.info(
        "Done: imported=%d skipped_existing=%d published=%d queue=%s",
        imported,
        skipped,
        published,
        config.queue if not config.no_publish else "<disabled>",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
